// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20250221231816_up = [
  InsertTable('RecipeStep'),
  InsertTable('User'),
  InsertTable('RecipeIngredient'),
  InsertTable('Household'),
  InsertTable('SharedPermission'),
  InsertTable('RecipeStepImageMapping'),
  InsertTable('RecipeImage'),
  InsertTable('RecipeFolder'),
  InsertTable('Recipe'),
  InsertForeignKey('RecipeStep', 'Recipe', foreignKeyColumn: 'recipe_Recipe_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('position', Column.integer, onTable: 'RecipeStep'),
  InsertColumn('entry_type', Column.varchar, onTable: 'RecipeStep'),
  InsertColumn('text', Column.varchar, onTable: 'RecipeStep'),
  InsertColumn('timer_duration', Column.integer, onTable: 'RecipeStep'),
  InsertColumn('id', Column.varchar, onTable: 'RecipeStep', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'User'),
  InsertColumn('email', Column.varchar, onTable: 'User'),
  InsertColumn('id', Column.varchar, onTable: 'User', unique: true),
  InsertForeignKey('User', 'Household', foreignKeyColumn: 'household_Household_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('recipe_id', Column.varchar, onTable: 'RecipeIngredient'),
  InsertColumn('position', Column.integer, onTable: 'RecipeIngredient'),
  InsertColumn('entry_type', Column.varchar, onTable: 'RecipeIngredient'),
  InsertColumn('text', Column.varchar, onTable: 'RecipeIngredient'),
  InsertColumn('note', Column.varchar, onTable: 'RecipeIngredient'),
  InsertColumn('unit1', Column.varchar, onTable: 'RecipeIngredient'),
  InsertColumn('quantity1', Column.Double, onTable: 'RecipeIngredient'),
  InsertColumn('unit2', Column.varchar, onTable: 'RecipeIngredient'),
  InsertColumn('quantity2', Column.Double, onTable: 'RecipeIngredient'),
  InsertColumn('total_unit', Column.varchar, onTable: 'RecipeIngredient'),
  InsertColumn('total_quantity', Column.Double, onTable: 'RecipeIngredient'),
  InsertColumn('id', Column.varchar, onTable: 'RecipeIngredient', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Household'),
  InsertColumn('id', Column.varchar, onTable: 'Household', unique: true),
  InsertColumn('id', Column.varchar, onTable: 'SharedPermission', unique: true),
  InsertColumn('entity_type', Column.varchar, onTable: 'SharedPermission'),
  InsertColumn('entity_id', Column.varchar, onTable: 'SharedPermission'),
  InsertColumn('owner_id', Column.varchar, onTable: 'SharedPermission'),
  InsertColumn('target_user_id', Column.varchar, onTable: 'SharedPermission'),
  InsertColumn('access_level', Column.varchar, onTable: 'SharedPermission'),
  InsertForeignKey('RecipeStepImageMapping', 'RecipeStep', foreignKeyColumn: 'step_RecipeStep_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertForeignKey('RecipeStepImageMapping', 'RecipeImage', foreignKeyColumn: 'image_RecipeImage_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('id', Column.varchar, onTable: 'RecipeStepImageMapping', unique: true),
  InsertForeignKey('RecipeImage', 'Recipe', foreignKeyColumn: 'recipe_Recipe_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('image_url', Column.varchar, onTable: 'RecipeImage'),
  InsertColumn('is_cover', Column.boolean, onTable: 'RecipeImage'),
  InsertColumn('id', Column.varchar, onTable: 'RecipeImage', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'RecipeFolder'),
  InsertColumn('id', Column.varchar, onTable: 'RecipeFolder', unique: true),
  InsertColumn('parent_id', Column.varchar, onTable: 'RecipeFolder'),
  InsertColumn('user_id', Column.varchar, onTable: 'RecipeFolder'),
  InsertColumn('household_id', Column.varchar, onTable: 'RecipeFolder'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'RecipeFolder'),
  InsertColumn('title', Column.varchar, onTable: 'Recipe'),
  InsertColumn('description', Column.varchar, onTable: 'Recipe'),
  InsertColumn('rating', Column.integer, onTable: 'Recipe'),
  InsertColumn('language', Column.varchar, onTable: 'Recipe'),
  InsertColumn('servings', Column.integer, onTable: 'Recipe'),
  InsertColumn('prep_time', Column.integer, onTable: 'Recipe'),
  InsertColumn('cook_time', Column.integer, onTable: 'Recipe'),
  InsertColumn('total_time', Column.integer, onTable: 'Recipe'),
  InsertColumn('source', Column.varchar, onTable: 'Recipe'),
  InsertColumn('nutrition', Column.varchar, onTable: 'Recipe'),
  InsertColumn('general_notes', Column.varchar, onTable: 'Recipe'),
  InsertColumn('user_id', Column.varchar, onTable: 'Recipe'),
  InsertForeignKey('Recipe', 'RecipeFolder', foreignKeyColumn: 'folder_RecipeFolder_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertForeignKey('Recipe', 'Household', foreignKeyColumn: 'household_Household_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('created_at', Column.datetime, onTable: 'Recipe'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Recipe'),
  InsertColumn('id', Column.varchar, onTable: 'Recipe', unique: true),
  CreateIndex(columns: ['id'], onTable: 'RecipeStep', unique: true),
  CreateIndex(columns: ['id'], onTable: 'User', unique: true),
  CreateIndex(columns: ['id'], onTable: 'RecipeIngredient', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Household', unique: true),
  CreateIndex(columns: ['id'], onTable: 'SharedPermission', unique: true),
  CreateIndex(columns: ['owner_id'], onTable: 'SharedPermission', unique: false),
  CreateIndex(columns: ['target_user_id'], onTable: 'SharedPermission', unique: false),
  CreateIndex(columns: ['id'], onTable: 'RecipeStepImageMapping', unique: true),
  CreateIndex(columns: ['id'], onTable: 'RecipeImage', unique: true),
  CreateIndex(columns: ['id'], onTable: 'RecipeFolder', unique: true),
  CreateIndex(columns: ['user_id'], onTable: 'RecipeFolder', unique: false),
  CreateIndex(columns: ['household_id'], onTable: 'RecipeFolder', unique: false),
  CreateIndex(columns: ['deleted_at'], onTable: 'RecipeFolder', unique: false),
  CreateIndex(columns: ['user_id'], onTable: 'Recipe', unique: false),
  CreateIndex(columns: ['id'], onTable: 'Recipe', unique: true)
];

const List<MigrationCommand> _migration_20250221231816_down = [
  DropTable('RecipeStep'),
  DropTable('User'),
  DropTable('RecipeIngredient'),
  DropTable('Household'),
  DropTable('SharedPermission'),
  DropTable('RecipeStepImageMapping'),
  DropTable('RecipeImage'),
  DropTable('RecipeFolder'),
  DropTable('Recipe'),
  DropColumn('recipe_Recipe_brick_id', onTable: 'RecipeStep'),
  DropColumn('position', onTable: 'RecipeStep'),
  DropColumn('entry_type', onTable: 'RecipeStep'),
  DropColumn('text', onTable: 'RecipeStep'),
  DropColumn('timer_duration', onTable: 'RecipeStep'),
  DropColumn('id', onTable: 'RecipeStep'),
  DropColumn('name', onTable: 'User'),
  DropColumn('email', onTable: 'User'),
  DropColumn('id', onTable: 'User'),
  DropColumn('household_Household_brick_id', onTable: 'User'),
  DropColumn('recipe_id', onTable: 'RecipeIngredient'),
  DropColumn('position', onTable: 'RecipeIngredient'),
  DropColumn('entry_type', onTable: 'RecipeIngredient'),
  DropColumn('text', onTable: 'RecipeIngredient'),
  DropColumn('note', onTable: 'RecipeIngredient'),
  DropColumn('unit1', onTable: 'RecipeIngredient'),
  DropColumn('quantity1', onTable: 'RecipeIngredient'),
  DropColumn('unit2', onTable: 'RecipeIngredient'),
  DropColumn('quantity2', onTable: 'RecipeIngredient'),
  DropColumn('total_unit', onTable: 'RecipeIngredient'),
  DropColumn('total_quantity', onTable: 'RecipeIngredient'),
  DropColumn('id', onTable: 'RecipeIngredient'),
  DropColumn('name', onTable: 'Household'),
  DropColumn('id', onTable: 'Household'),
  DropColumn('id', onTable: 'SharedPermission'),
  DropColumn('entity_type', onTable: 'SharedPermission'),
  DropColumn('entity_id', onTable: 'SharedPermission'),
  DropColumn('owner_id', onTable: 'SharedPermission'),
  DropColumn('target_user_id', onTable: 'SharedPermission'),
  DropColumn('access_level', onTable: 'SharedPermission'),
  DropColumn('step_RecipeStep_brick_id', onTable: 'RecipeStepImageMapping'),
  DropColumn('image_RecipeImage_brick_id', onTable: 'RecipeStepImageMapping'),
  DropColumn('id', onTable: 'RecipeStepImageMapping'),
  DropColumn('recipe_Recipe_brick_id', onTable: 'RecipeImage'),
  DropColumn('image_url', onTable: 'RecipeImage'),
  DropColumn('is_cover', onTable: 'RecipeImage'),
  DropColumn('id', onTable: 'RecipeImage'),
  DropColumn('name', onTable: 'RecipeFolder'),
  DropColumn('id', onTable: 'RecipeFolder'),
  DropColumn('parent_id', onTable: 'RecipeFolder'),
  DropColumn('user_id', onTable: 'RecipeFolder'),
  DropColumn('household_id', onTable: 'RecipeFolder'),
  DropColumn('deleted_at', onTable: 'RecipeFolder'),
  DropColumn('title', onTable: 'Recipe'),
  DropColumn('description', onTable: 'Recipe'),
  DropColumn('rating', onTable: 'Recipe'),
  DropColumn('language', onTable: 'Recipe'),
  DropColumn('servings', onTable: 'Recipe'),
  DropColumn('prep_time', onTable: 'Recipe'),
  DropColumn('cook_time', onTable: 'Recipe'),
  DropColumn('total_time', onTable: 'Recipe'),
  DropColumn('source', onTable: 'Recipe'),
  DropColumn('nutrition', onTable: 'Recipe'),
  DropColumn('general_notes', onTable: 'Recipe'),
  DropColumn('user_id', onTable: 'Recipe'),
  DropColumn('folder_RecipeFolder_brick_id', onTable: 'Recipe'),
  DropColumn('household_Household_brick_id', onTable: 'Recipe'),
  DropColumn('created_at', onTable: 'Recipe'),
  DropColumn('updated_at', onTable: 'Recipe'),
  DropColumn('id', onTable: 'Recipe'),
  DropIndex('index_RecipeStep_on_id'),
  DropIndex('index_User_on_id'),
  DropIndex('index_RecipeIngredient_on_id'),
  DropIndex('index_Household_on_id'),
  DropIndex('index_SharedPermission_on_id'),
  DropIndex('index_SharedPermission_on_owner_id'),
  DropIndex('index_SharedPermission_on_target_user_id'),
  DropIndex('index_RecipeStepImageMapping_on_id'),
  DropIndex('index_RecipeImage_on_id'),
  DropIndex('index_RecipeFolder_on_id'),
  DropIndex('index_RecipeFolder_on_user_id'),
  DropIndex('index_RecipeFolder_on_household_id'),
  DropIndex('index_RecipeFolder_on_deleted_at'),
  DropIndex('index_Recipe_on_user_id'),
  DropIndex('index_Recipe_on_id')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20250221231816',
  up: _migration_20250221231816_up,
  down: _migration_20250221231816_down,
)
class Migration20250221231816 extends Migration {
  const Migration20250221231816()
    : super(
        version: 20250221231816,
        up: _migration_20250221231816_up,
        down: _migration_20250221231816_down,
      );
}
