version: '3.8'

services:
  powersync:
    profiles:
      - disabled
    restart: unless-stopped
    image: journeyapps/powersync-service:latest
    command: ["start", "-r", "unified"]
    volumes:
      - ./config:/config
    environment:
      POWERSYNC_CONFIG_PATH: /config/powersync.yaml
      NODE_OPTIONS: --max-old-space-size=1000
      PS_DATA_SOURCE_URI: ${PS_DATA_SOURCE_URI}
      PS_MONGO_URI: mongodb://mongo:27017/powersync_demo
      PS_JWKS_URL: ${PS_JWKS_URL}
      PS_PORT: ${PS_PORT}
      PS_SUPABASE_JWT_SECRET: ${PS_SUPABASE_JWT_SECRET}
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://localhost:${PS_PORT}/probes/liveness').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"
        ]
      interval: 5s
      timeout: 1s
      retries: 15
    ports:
      - ${PS_PORT}:${PS_PORT}
