// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7gwNrCCDCtNW7f9fxxbwFfZPqbSibRcY',
    appId: '1:188524317472:web:7f1664c70ad0003b1ea545',
    messagingSenderId: '188524317472',
    projectId: 'recipe-app-449111',
    authDomain: 'recipe-app-449111.firebaseapp.com',
    storageBucket: 'recipe-app-449111.firebasestorage.app',
    measurementId: 'G-H2DNZXGZDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABTEof8Mhmhl9mXBX1jZEjdEFXQv9YV0Y',
    appId: '1:188524317472:android:9b0fc31080632a811ea545',
    messagingSenderId: '188524317472',
    projectId: 'recipe-app-449111',
    storageBucket: 'recipe-app-449111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr0175SzpIp8LpKXhO-qx47Ky1s465Nio',
    appId: '1:188524317472:ios:c69e96d82807fb0a1ea545',
    messagingSenderId: '188524317472',
    projectId: 'recipe-app-449111',
    storageBucket: 'recipe-app-449111.firebasestorage.app',
    iosBundleId: 'com.mattcarpenter.RecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr0175SzpIp8LpKXhO-qx47Ky1s465Nio',
    appId: '1:188524317472:ios:d25ea6420fe45a041ea545',
    messagingSenderId: '188524317472',
    projectId: 'recipe-app-449111',
    storageBucket: 'recipe-app-449111.firebasestorage.app',
    iosBundleId: 'net.mattcarpenter.flutterTest2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7gwNrCCDCtNW7f9fxxbwFfZPqbSibRcY',
    appId: '1:188524317472:web:2c1e41c80442393c1ea545',
    messagingSenderId: '188524317472',
    projectId: 'recipe-app-449111',
    authDomain: 'recipe-app-449111.firebaseapp.com',
    storageBucket: 'recipe-app-449111.firebasestorage.app',
    measurementId: 'G-YRZHLG8PZ6',
  );

}