// Mocks generated by Mockito 5.4.6 from annotations
// in recipe_app/test/features/import_export/services/import_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:recipe_app/database/database.dart' as _i3;
import 'package:recipe_app/database/models/ingredients.dart' as _i7;
import 'package:recipe_app/database/models/steps.dart' as _i8;
import 'package:recipe_app/src/managers/ingredient_term_queue_manager.dart'
    as _i5;
import 'package:recipe_app/src/models/ingredient_pantry_match.dart' as _i2;
import 'package:recipe_app/src/models/ingredient_term_search_result.dart'
    as _i13;
import 'package:recipe_app/src/models/recipe_pantry_match.dart' as _i10;
import 'package:recipe_app/src/models/recipe_with_folders.dart' as _i9;
import 'package:recipe_app/src/repositories/recipe_folder_repository.dart'
    as _i12;
import 'package:recipe_app/src/repositories/recipe_repository.dart' as _i4;
import 'package:recipe_app/src/repositories/recipe_tag_repository.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRecipeIngredientMatches_0 extends _i1.SmartFake
    implements _i2.RecipeIngredientMatches {
  _FakeRecipeIngredientMatches_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecipeTagEntry_1 extends _i1.SmartFake
    implements _i3.RecipeTagEntry {
  _FakeRecipeTagEntry_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecipeFolderEntry_2 extends _i1.SmartFake
    implements _i3.RecipeFolderEntry {
  _FakeRecipeFolderEntry_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RecipeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeRepository extends _i1.Mock implements _i4.RecipeRepository {
  MockRecipeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set ingredientTermQueueManager(_i5.IngredientTermQueueManager? manager) =>
      super.noSuchMethod(
        Invocation.setter(
          #ingredientTermQueueManager,
          manager,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Stream<List<_i3.RecipeEntry>> watchAllRecipes() => (super.noSuchMethod(
        Invocation.method(
          #watchAllRecipes,
          [],
        ),
        returnValue: _i6.Stream<List<_i3.RecipeEntry>>.empty(),
      ) as _i6.Stream<List<_i3.RecipeEntry>>);

  @override
  _i6.Future<int> addRecipe(_i3.RecipesCompanion? recipe) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRecipe,
          [recipe],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> updateRecipe(_i3.RecipeEntry? recipe) => (super.noSuchMethod(
        Invocation.method(
          #updateRecipe,
          [recipe],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i3.RecipeEntry?> getRecipeById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getRecipeById,
          [id],
        ),
        returnValue: _i6.Future<_i3.RecipeEntry?>.value(),
      ) as _i6.Future<_i3.RecipeEntry?>);

  @override
  _i6.Future<_i3.RecipeEntry?> getRecipeByTitle(String? title) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeByTitle,
          [title],
        ),
        returnValue: _i6.Future<_i3.RecipeEntry?>.value(),
      ) as _i6.Future<_i3.RecipeEntry?>);

  @override
  _i6.Future<bool> updateImageForRecipe({
    required String? recipeId,
    required String? fileName,
    required String? publicUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateImageForRecipe,
          [],
          {
            #recipeId: recipeId,
            #fileName: fileName,
            #publicUrl: publicUrl,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> deleteRecipe(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRecipe,
          [id],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> addFolderToRecipe({
    required String? recipeId,
    required String? folderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFolderToRecipe,
          [],
          {
            #recipeId: recipeId,
            #folderId: folderId,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeFolderFromRecipe({
    required String? recipeId,
    required String? folderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFolderFromRecipe,
          [],
          {
            #recipeId: recipeId,
            #folderId: folderId,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> updateIngredients(
    String? recipeId,
    List<_i7.Ingredient>? ingredients,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIngredients,
          [
            recipeId,
            ingredients,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> updateSteps(
    String? recipeId,
    List<_i8.Step>? steps,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSteps,
          [
            recipeId,
            steps,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Stream<List<_i9.RecipeWithFolders>> watchRecipesWithFolders() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRecipesWithFolders,
          [],
        ),
        returnValue: _i6.Stream<List<_i9.RecipeWithFolders>>.empty(),
      ) as _i6.Stream<List<_i9.RecipeWithFolders>>);

  @override
  _i6.Stream<List<_i9.RecipeWithFolders>> watchRecipesByFolderId(
          String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRecipesByFolderId,
          [folderId],
        ),
        returnValue: _i6.Stream<List<_i9.RecipeWithFolders>>.empty(),
      ) as _i6.Stream<List<_i9.RecipeWithFolders>>);

  @override
  _i6.Stream<_i3.RecipeEntry?> watchRecipeById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRecipeById,
          [id],
        ),
        returnValue: _i6.Stream<_i3.RecipeEntry?>.empty(),
      ) as _i6.Stream<_i3.RecipeEntry?>);

  @override
  _i6.Future<void> removeFolderIdFromAllRecipes(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFolderIdFromAllRecipes,
          [folderId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeTagIdFromAllRecipes(String? tagId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTagIdFromAllRecipes,
          [tagId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.RecipeEntry>> searchRecipes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRecipes,
          [query],
        ),
        returnValue:
            _i6.Future<List<_i3.RecipeEntry>>.value(<_i3.RecipeEntry>[]),
      ) as _i6.Future<List<_i3.RecipeEntry>>);

  @override
  _i6.Future<List<_i10.RecipePantryMatch>> findMatchingRecipesFromPantry() =>
      (super.noSuchMethod(
        Invocation.method(
          #findMatchingRecipesFromPantry,
          [],
        ),
        returnValue: _i6.Future<List<_i10.RecipePantryMatch>>.value(
            <_i10.RecipePantryMatch>[]),
      ) as _i6.Future<List<_i10.RecipePantryMatch>>);

  @override
  _i6.Future<_i2.RecipeIngredientMatches> findPantryMatchesForRecipe(
          String? recipeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findPantryMatchesForRecipe,
          [recipeId],
        ),
        returnValue: _i6.Future<_i2.RecipeIngredientMatches>.value(
            _FakeRecipeIngredientMatches_0(
          this,
          Invocation.method(
            #findPantryMatchesForRecipe,
            [recipeId],
          ),
        )),
      ) as _i6.Future<_i2.RecipeIngredientMatches>);

  @override
  _i6.Future<List<_i3.RecipeEntry>> getRecipesByIds(List<String>? recipeIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipesByIds,
          [recipeIds],
        ),
        returnValue:
            _i6.Future<List<_i3.RecipeEntry>>.value(<_i3.RecipeEntry>[]),
      ) as _i6.Future<List<_i3.RecipeEntry>>);

  @override
  _i6.Future<bool> toggleRecipePin(
    String? recipeId,
    bool? pinned,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleRecipePin,
          [
            recipeId,
            pinned,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i3.RecipeEntry>> getPinnedRecipes({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPinnedRecipes,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i6.Future<List<_i3.RecipeEntry>>.value(<_i3.RecipeEntry>[]),
      ) as _i6.Future<List<_i3.RecipeEntry>>);

  @override
  _i6.Stream<List<_i3.RecipeEntry>> watchPinnedRecipes({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchPinnedRecipes,
          [],
          {#limit: limit},
        ),
        returnValue: _i6.Stream<List<_i3.RecipeEntry>>.empty(),
      ) as _i6.Stream<List<_i3.RecipeEntry>>);
}

/// A class which mocks [RecipeTagRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeTagRepository extends _i1.Mock
    implements _i11.RecipeTagRepository {
  MockRecipeTagRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<List<_i3.RecipeTagEntry>> watchTags() => (super.noSuchMethod(
        Invocation.method(
          #watchTags,
          [],
        ),
        returnValue: _i6.Stream<List<_i3.RecipeTagEntry>>.empty(),
      ) as _i6.Stream<List<_i3.RecipeTagEntry>>);

  @override
  _i6.Future<_i3.RecipeTagEntry> addTag({
    required String? name,
    required String? color,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTag,
          [],
          {
            #name: name,
            #color: color,
            #userId: userId,
          },
        ),
        returnValue: _i6.Future<_i3.RecipeTagEntry>.value(_FakeRecipeTagEntry_1(
          this,
          Invocation.method(
            #addTag,
            [],
            {
              #name: name,
              #color: color,
              #userId: userId,
            },
          ),
        )),
      ) as _i6.Future<_i3.RecipeTagEntry>);

  @override
  _i6.Future<void> updateTag({
    required String? tagId,
    String? name,
    String? color,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTag,
          [],
          {
            #tagId: tagId,
            #name: name,
            #color: color,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteTag(String? tagId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTag,
          [tagId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteTagAndCleanupReferences(
    String? tagId,
    _i4.RecipeRepository? recipeRepository,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTagAndCleanupReferences,
          [
            tagId,
            recipeRepository,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.RecipeTagEntry?> getTagById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTagById,
          [id],
        ),
        returnValue: _i6.Future<_i3.RecipeTagEntry?>.value(),
      ) as _i6.Future<_i3.RecipeTagEntry?>);

  @override
  _i6.Future<List<_i3.RecipeTagEntry>> getTagsByIds(List<String>? tagIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTagsByIds,
          [tagIds],
        ),
        returnValue:
            _i6.Future<List<_i3.RecipeTagEntry>>.value(<_i3.RecipeTagEntry>[]),
      ) as _i6.Future<List<_i3.RecipeTagEntry>>);

  @override
  _i6.Future<Map<String, int>> getRecipeCountsByTag() => (super.noSuchMethod(
        Invocation.method(
          #getRecipeCountsByTag,
          [],
        ),
        returnValue: _i6.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i6.Future<Map<String, int>>);

  @override
  _i6.Future<int> getRecipeCountForTag(String? tagId) => (super.noSuchMethod(
        Invocation.method(
          #getRecipeCountForTag,
          [tagId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);
}

/// A class which mocks [RecipeFolderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeFolderRepository extends _i1.Mock
    implements _i12.RecipeFolderRepository {
  MockRecipeFolderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<List<_i3.RecipeFolderEntry>> watchFolders() => (super.noSuchMethod(
        Invocation.method(
          #watchFolders,
          [],
        ),
        returnValue: _i6.Stream<List<_i3.RecipeFolderEntry>>.empty(),
      ) as _i6.Stream<List<_i3.RecipeFolderEntry>>);

  @override
  _i6.Future<_i3.RecipeFolderEntry> addFolder({
    required String? name,
    String? userId,
    String? householdId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFolder,
          [],
          {
            #name: name,
            #userId: userId,
            #householdId: householdId,
          },
        ),
        returnValue:
            _i6.Future<_i3.RecipeFolderEntry>.value(_FakeRecipeFolderEntry_2(
          this,
          Invocation.method(
            #addFolder,
            [],
            {
              #name: name,
              #userId: userId,
              #householdId: householdId,
            },
          ),
        )),
      ) as _i6.Future<_i3.RecipeFolderEntry>);

  @override
  _i6.Future<int> deleteFolder(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFolder,
          [id],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> renameFolder(
    String? id,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameFolder,
          [
            id,
            newName,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> deleteFolderAndCleanupReferences(
    String? folderId,
    _i4.RecipeRepository? recipeRepository,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFolderAndCleanupReferences,
          [
            folderId,
            recipeRepository,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.RecipeFolderEntry> addSmartFolder({
    required String? name,
    required int? folderType,
    required int? filterLogic,
    List<String>? tags,
    List<String>? terms,
    String? userId,
    String? householdId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSmartFolder,
          [],
          {
            #name: name,
            #folderType: folderType,
            #filterLogic: filterLogic,
            #tags: tags,
            #terms: terms,
            #userId: userId,
            #householdId: householdId,
          },
        ),
        returnValue:
            _i6.Future<_i3.RecipeFolderEntry>.value(_FakeRecipeFolderEntry_2(
          this,
          Invocation.method(
            #addSmartFolder,
            [],
            {
              #name: name,
              #folderType: folderType,
              #filterLogic: filterLogic,
              #tags: tags,
              #terms: terms,
              #userId: userId,
              #householdId: householdId,
            },
          ),
        )),
      ) as _i6.Future<_i3.RecipeFolderEntry>);

  @override
  _i6.Future<int> updateSmartFolderSettings({
    required String? id,
    String? name,
    int? filterLogic,
    List<String>? tags,
    List<String>? terms,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSmartFolderSettings,
          [],
          {
            #id: id,
            #name: name,
            #filterLogic: filterLogic,
            #tags: tags,
            #terms: terms,
          },
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i3.RecipeEntry>> getRecipesForTagSmartFolder({
    required List<String>? tagNames,
    required bool? matchAll,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipesForTagSmartFolder,
          [],
          {
            #tagNames: tagNames,
            #matchAll: matchAll,
          },
        ),
        returnValue:
            _i6.Future<List<_i3.RecipeEntry>>.value(<_i3.RecipeEntry>[]),
      ) as _i6.Future<List<_i3.RecipeEntry>>);

  @override
  _i6.Future<List<_i3.RecipeEntry>> getRecipesForIngredientSmartFolder({
    required List<String>? terms,
    required bool? matchAll,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipesForIngredientSmartFolder,
          [],
          {
            #terms: terms,
            #matchAll: matchAll,
          },
        ),
        returnValue:
            _i6.Future<List<_i3.RecipeEntry>>.value(<_i3.RecipeEntry>[]),
      ) as _i6.Future<List<_i3.RecipeEntry>>);

  @override
  _i6.Future<List<_i13.IngredientTermSearchResult>> searchIngredientTerms(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchIngredientTerms,
          [query],
        ),
        returnValue: _i6.Future<List<_i13.IngredientTermSearchResult>>.value(
            <_i13.IngredientTermSearchResult>[]),
      ) as _i6.Future<List<_i13.IngredientTermSearchResult>>);
}
