import 'package:drift/drift.dart';
import 'package:uuid/uuid.dart';

import '../database.dart';

/// Timer entries for tracking active cooking timers.
/// This is a LOCAL ONLY table - timers are device-specific and not synced.
@DataClassName('TimerEntry')
class Timers extends Table {
  // Primary key with client-side UUID
  TextColumn get id =>
      text().clientDefault(() => const Uuid().v4()).unique()();

  @override
  Set<Column> get primaryKey => {id};

  // Recipe reference
  TextColumn get recipeId => text()();
  TextColumn get recipeName => text()();

  // Step reference
  TextColumn get stepId => text()();
  IntColumn get stepNumber => integer()(); // 1-indexed display number
  IntColumn get totalSteps => integer()(); // Total steps in recipe

  // Timer details
  TextColumn get detectedText =>
      text()(); // Original matched text (e.g., "25 minutes")
  IntColumn get durationSeconds => integer()(); // Original duration in seconds
  IntColumn get endTimestamp => integer()(); // Unix timestamp (ms) when timer expires

  // Metadata
  IntColumn get createdAt => integer()(); // When timer was started
  TextColumn get notificationId =>
      text().nullable()(); // Platform notification ID for cancellation
}

/// Extension methods for TimerEntry.
/// Note: TimerEntry is generated by Drift from the Timers table.
extension TimerEntryExtension on TimerEntry {
  /// Time remaining until expiration
  Duration get remaining {
    final now = DateTime.now().millisecondsSinceEpoch;
    final diff = endTimestamp - now;
    return Duration(milliseconds: diff.clamp(0, endTimestamp));
  }

  /// Whether timer is still active (not expired)
  bool get isActive => remaining.inMilliseconds > 0;

  /// Whether timer has expired
  bool get isExpired => !isActive;

  /// Original duration as Duration object
  Duration get originalDuration => Duration(seconds: durationSeconds);

  /// Format step as "X of Y"
  String get stepDisplay => '$stepNumber of $totalSteps';

  /// Format remaining time as MM:SS or HH:MM:SS
  String get formattedRemaining {
    final rem = remaining;
    final hours = rem.inHours;
    final minutes = rem.inMinutes.remainder(60);
    final seconds = rem.inSeconds.remainder(60);

    if (hours > 0) {
      return '$hours:${minutes.toString().padLeft(2, '0')}:${seconds.toString().padLeft(2, '0')}';
    }
    return '$minutes:${seconds.toString().padLeft(2, '0')}';
  }
}
