import 'package:drift/drift.dart';
import 'package:uuid/uuid.dart';

@DataClassName('UploadQueueEntry')
class UploadQueues extends Table {
  // Unique identifier (default generated by the client)
  TextColumn get id =>
      text().clientDefault(() => const Uuid().v4()).unique()();

  // The filename (stored in your app’s documents directory)
  TextColumn get fileName => text()();

  // Status: pending, uploading, uploaded, or failed.
  TextColumn get status => text().withDefault(Constant('pending'))();

  // Retry count for failed uploads.
  IntColumn get retryCount => integer().withDefault(Constant(0))();

  // Last time an upload was attempted (stored as epoch milliseconds)
  IntColumn get lastTryTimestamp => integer().nullable()();

  // Optional: associated recipe ID (null if the recipe isn’t saved yet)
  TextColumn get recipeId => text().nullable()();
}
