// Mocks generated by Mockito 5.4.5 from annotations
// in recipe_app/test/unit/upload_queue_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i17;
import 'dart:typed_data' as _i18;

import 'package:drift/drift.dart' as _i4;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:recipe_app/database/database.dart' as _i3;
import 'package:recipe_app/database/models/ingredients.dart' as _i13;
import 'package:recipe_app/database/models/steps.dart' as _i14;
import 'package:recipe_app/src/managers/ingredient_term_queue_manager.dart'
    as _i12;
import 'package:recipe_app/src/models/ingredient_pantry_match.dart' as _i2;
import 'package:recipe_app/src/models/recipe_pantry_match.dart' as _i16;
import 'package:recipe_app/src/models/recipe_with_folders.dart' as _i15;
import 'package:recipe_app/src/repositories/recipe_repository.dart' as _i11;
import 'package:recipe_app/src/repositories/upload_queue_repository.dart'
    as _i9;
import 'package:storage_client/src/fetch.dart' as _i8;
import 'package:supabase/supabase.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRecipeIngredientMatches_0 extends _i1.SmartFake
    implements _i2.RecipeIngredientMatches {
  _FakeRecipeIngredientMatches_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$RecipeFoldersTable_1 extends _i1.SmartFake
    implements _i3.$RecipeFoldersTable {
  _Fake$RecipeFoldersTable_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$RecipesTable_2 extends _i1.SmartFake implements _i3.$RecipesTable {
  _Fake$RecipesTable_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$RecipeSharesTable_3 extends _i1.SmartFake
    implements _i3.$RecipeSharesTable {
  _Fake$RecipeSharesTable_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$HouseholdMembersTable_4 extends _i1.SmartFake
    implements _i3.$HouseholdMembersTable {
  _Fake$HouseholdMembersTable_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$HouseholdsTable_5 extends _i1.SmartFake
    implements _i3.$HouseholdsTable {
  _Fake$HouseholdsTable_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$HouseholdInvitesTable_6 extends _i1.SmartFake
    implements _i3.$HouseholdInvitesTable {
  _Fake$HouseholdInvitesTable_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$UploadQueuesTable_7 extends _i1.SmartFake
    implements _i3.$UploadQueuesTable {
  _Fake$UploadQueuesTable_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$IngredientTermQueuesTable_8 extends _i1.SmartFake
    implements _i3.$IngredientTermQueuesTable {
  _Fake$IngredientTermQueuesTable_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$PantryItemTermQueuesTable_9 extends _i1.SmartFake
    implements _i3.$PantryItemTermQueuesTable {
  _Fake$PantryItemTermQueuesTable_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ShoppingListItemTermQueuesTable_10 extends _i1.SmartFake
    implements _i3.$ShoppingListItemTermQueuesTable {
  _Fake$ShoppingListItemTermQueuesTable_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$CooksTable_11 extends _i1.SmartFake implements _i3.$CooksTable {
  _Fake$CooksTable_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$PantryItemsTable_12 extends _i1.SmartFake
    implements _i3.$PantryItemsTable {
  _Fake$PantryItemsTable_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$IngredientTermOverridesTable_13 extends _i1.SmartFake
    implements _i3.$IngredientTermOverridesTable {
  _Fake$IngredientTermOverridesTable_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ShoppingListItemsTable_14 extends _i1.SmartFake
    implements _i3.$ShoppingListItemsTable {
  _Fake$ShoppingListItemsTable_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ShoppingListsTable_15 extends _i1.SmartFake
    implements _i3.$ShoppingListsTable {
  _Fake$ShoppingListsTable_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ConvertersTable_16 extends _i1.SmartFake
    implements _i3.$ConvertersTable {
  _Fake$ConvertersTable_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$MealPlansTable_17 extends _i1.SmartFake
    implements _i3.$MealPlansTable {
  _Fake$MealPlansTable_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AppDatabaseManager_18 extends _i1.SmartFake
    implements _i3.$AppDatabaseManager {
  _Fake$AppDatabaseManager_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedDatabase_19 extends _i1.SmartFake
    implements _i4.GeneratedDatabase {
  _FakeGeneratedDatabase_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_20 extends _i1.SmartFake
    implements _i4.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrationStrategy_21 extends _i1.SmartFake
    implements _i4.MigrationStrategy {
  _FakeMigrationStrategy_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryUpdateRules_22 extends _i1.SmartFake
    implements _i4.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_23 extends _i1.SmartFake
    implements _i4.DatabaseConnection {
  _FakeDatabaseConnection_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_24 extends _i1.SmartFake implements _i4.QueryExecutor {
  _FakeQueryExecutor_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_25 extends _i1.SmartFake
    implements _i5.StreamQueryStore {
  _FakeStreamQueryStore_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_26 extends _i1.SmartFake
    implements _i4.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrator_27 extends _i1.SmartFake implements _i4.Migrator {
  _FakeMigrator_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_28<T1> extends _i1.SmartFake implements _i6.Future<T1> {
  _FakeFuture_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_29<T1 extends _i4.Table, D1> extends _i1.SmartFake
    implements _i4.InsertStatement<T1, D1> {
  _FakeInsertStatement_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_30<T extends _i4.Table, D> extends _i1.SmartFake
    implements _i4.UpdateStatement<T, D> {
  _FakeUpdateStatement_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_31<T1 extends _i4.HasResultSet, D>
    extends _i1.SmartFake implements _i4.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_32<FirstT extends _i4.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i4.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseSelectStatement_33<Row> extends _i1.SmartFake
    implements _i4.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_34<T1 extends _i4.Table, D1> extends _i1.SmartFake
    implements _i4.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_35<T> extends _i1.SmartFake implements _i4.Selectable<T> {
  _FakeSelectable_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_36 extends _i1.SmartFake
    implements _i4.GenerationContext {
  _FakeGenerationContext_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFunctionsClient_37 extends _i1.SmartFake
    implements _i7.FunctionsClient {
  _FakeFunctionsClient_37(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseStorageClient_38 extends _i1.SmartFake
    implements _i7.SupabaseStorageClient {
  _FakeSupabaseStorageClient_38(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeClient_39 extends _i1.SmartFake
    implements _i7.RealtimeClient {
  _FakeRealtimeClient_39(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestClient_40 extends _i1.SmartFake
    implements _i7.PostgrestClient {
  _FakePostgrestClient_40(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueClient_41 extends _i1.SmartFake implements _i7.GoTrueClient {
  _FakeGoTrueClient_41(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQueryBuilder_42 extends _i1.SmartFake
    implements _i7.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_42(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQuerySchema_43 extends _i1.SmartFake
    implements _i7.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_43(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestFilterBuilder_44<T1> extends _i1.SmartFake
    implements _i7.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_44(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeChannel_45 extends _i1.SmartFake
    implements _i7.RealtimeChannel {
  _FakeRealtimeChannel_45(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueAdminApi_46 extends _i1.SmartFake
    implements _i7.GoTrueAdminApi {
  _FakeGoTrueAdminApi_46(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueMFAApi_47 extends _i1.SmartFake implements _i7.GoTrueMFAApi {
  _FakeGoTrueMFAApi_47(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResponse_48 extends _i1.SmartFake implements _i7.AuthResponse {
  _FakeAuthResponse_48(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOAuthResponse_49 extends _i1.SmartFake implements _i7.OAuthResponse {
  _FakeOAuthResponse_49(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthSessionUrlResponse_50 extends _i1.SmartFake
    implements _i7.AuthSessionUrlResponse {
  _FakeAuthSessionUrlResponse_50(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResendResponse_51 extends _i1.SmartFake
    implements _i7.ResendResponse {
  _FakeResendResponse_51(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserResponse_52 extends _i1.SmartFake implements _i7.UserResponse {
  _FakeUserResponse_52(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObject_53 extends _i1.SmartFake implements Object {
  _FakeObject_53(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFetch_54 extends _i1.SmartFake implements _i8.Fetch {
  _FakeFetch_54(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageFileApi_55 extends _i1.SmartFake
    implements _i7.StorageFileApi {
  _FakeStorageFileApi_55(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBucket_56 extends _i1.SmartFake implements _i7.Bucket {
  _FakeBucket_56(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignedUploadURLResponse_57 extends _i1.SmartFake
    implements _i7.SignedUploadURLResponse {
  _FakeSignedUploadURLResponse_57(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UploadQueueRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadQueueRepository extends _i1.Mock
    implements _i9.UploadQueueRepository {
  MockUploadQueueRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<int> insertUploadQueueEntry({
    required String? fileName,
    required String? recipeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertUploadQueueEntry,
          [],
          {
            #fileName: fileName,
            #recipeId: recipeId,
          },
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i3.UploadQueueEntry>> getPendingEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingEntries,
          [],
        ),
        returnValue: _i6.Future<List<_i3.UploadQueueEntry>>.value(
            <_i3.UploadQueueEntry>[]),
      ) as _i6.Future<List<_i3.UploadQueueEntry>>);

  @override
  _i6.Future<int> deleteEntryByFileName(String? fileName) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEntryByFileName,
          [fileName],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> updateEntry(_i3.UploadQueueEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [entry],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> markEntryAsUploaded(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markEntryAsUploaded,
          [id],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<String> resolveFullPath(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #resolveFullPath,
          [fileName],
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #resolveFullPath,
            [fileName],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i3.UploadQueueEntry?> getEntryByFileName(String? fileName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntryByFileName,
          [fileName],
        ),
        returnValue: _i6.Future<_i3.UploadQueueEntry?>.value(),
      ) as _i6.Future<_i3.UploadQueueEntry?>);
}

/// A class which mocks [RecipeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeRepository extends _i1.Mock implements _i11.RecipeRepository {
  MockRecipeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set ingredientTermQueueManager(_i12.IngredientTermQueueManager? manager) =>
      super.noSuchMethod(
        Invocation.setter(
          #ingredientTermQueueManager,
          manager,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Stream<List<_i3.RecipeEntry>> watchAllRecipes() => (super.noSuchMethod(
        Invocation.method(
          #watchAllRecipes,
          [],
        ),
        returnValue: _i6.Stream<List<_i3.RecipeEntry>>.empty(),
      ) as _i6.Stream<List<_i3.RecipeEntry>>);

  @override
  _i6.Future<int> addRecipe(_i3.RecipesCompanion? recipe) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRecipe,
          [recipe],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> updateRecipe(_i3.RecipeEntry? recipe) => (super.noSuchMethod(
        Invocation.method(
          #updateRecipe,
          [recipe],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i3.RecipeEntry?> getRecipeById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getRecipeById,
          [id],
        ),
        returnValue: _i6.Future<_i3.RecipeEntry?>.value(),
      ) as _i6.Future<_i3.RecipeEntry?>);

  @override
  _i6.Future<bool> updateImageForRecipe({
    required String? recipeId,
    required String? fileName,
    required String? publicUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateImageForRecipe,
          [],
          {
            #recipeId: recipeId,
            #fileName: fileName,
            #publicUrl: publicUrl,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> deleteRecipe(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRecipe,
          [id],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> addFolderToRecipe({
    required String? recipeId,
    required String? folderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFolderToRecipe,
          [],
          {
            #recipeId: recipeId,
            #folderId: folderId,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeFolderFromRecipe({
    required String? recipeId,
    required String? folderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFolderFromRecipe,
          [],
          {
            #recipeId: recipeId,
            #folderId: folderId,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> updateIngredients(
    String? recipeId,
    List<_i13.Ingredient>? ingredients,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIngredients,
          [
            recipeId,
            ingredients,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> updateSteps(
    String? recipeId,
    List<_i14.Step>? steps,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSteps,
          [
            recipeId,
            steps,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Stream<List<_i15.RecipeWithFolders>> watchRecipesWithFolders() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRecipesWithFolders,
          [],
        ),
        returnValue: _i6.Stream<List<_i15.RecipeWithFolders>>.empty(),
      ) as _i6.Stream<List<_i15.RecipeWithFolders>>);

  @override
  _i6.Stream<List<_i15.RecipeWithFolders>> watchRecipesByFolderId(
          String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRecipesByFolderId,
          [folderId],
        ),
        returnValue: _i6.Stream<List<_i15.RecipeWithFolders>>.empty(),
      ) as _i6.Stream<List<_i15.RecipeWithFolders>>);

  @override
  _i6.Stream<_i3.RecipeEntry?> watchRecipeById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRecipeById,
          [id],
        ),
        returnValue: _i6.Stream<_i3.RecipeEntry?>.empty(),
      ) as _i6.Stream<_i3.RecipeEntry?>);

  @override
  _i6.Future<void> removeFolderIdFromAllRecipes(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFolderIdFromAllRecipes,
          [folderId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.RecipeEntry>> searchRecipes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRecipes,
          [query],
        ),
        returnValue:
            _i6.Future<List<_i3.RecipeEntry>>.value(<_i3.RecipeEntry>[]),
      ) as _i6.Future<List<_i3.RecipeEntry>>);

  @override
  _i6.Future<List<_i16.RecipePantryMatch>> findMatchingRecipesFromPantry() =>
      (super.noSuchMethod(
        Invocation.method(
          #findMatchingRecipesFromPantry,
          [],
        ),
        returnValue: _i6.Future<List<_i16.RecipePantryMatch>>.value(
            <_i16.RecipePantryMatch>[]),
      ) as _i6.Future<List<_i16.RecipePantryMatch>>);

  @override
  _i6.Future<_i2.RecipeIngredientMatches> findPantryMatchesForRecipe(
          String? recipeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findPantryMatchesForRecipe,
          [recipeId],
        ),
        returnValue: _i6.Future<_i2.RecipeIngredientMatches>.value(
            _FakeRecipeIngredientMatches_0(
          this,
          Invocation.method(
            #findPantryMatchesForRecipe,
            [recipeId],
          ),
        )),
      ) as _i6.Future<_i2.RecipeIngredientMatches>);

  @override
  _i6.Future<List<_i3.RecipeEntry>> getRecipesByIds(List<String>? recipeIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipesByIds,
          [recipeIds],
        ),
        returnValue:
            _i6.Future<List<_i3.RecipeEntry>>.value(<_i3.RecipeEntry>[]),
      ) as _i6.Future<List<_i3.RecipeEntry>>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i3.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
      ) as int);

  @override
  _i3.$RecipeFoldersTable get recipeFolders => (super.noSuchMethod(
        Invocation.getter(#recipeFolders),
        returnValue: _Fake$RecipeFoldersTable_1(
          this,
          Invocation.getter(#recipeFolders),
        ),
      ) as _i3.$RecipeFoldersTable);

  @override
  _i3.$RecipesTable get recipes => (super.noSuchMethod(
        Invocation.getter(#recipes),
        returnValue: _Fake$RecipesTable_2(
          this,
          Invocation.getter(#recipes),
        ),
      ) as _i3.$RecipesTable);

  @override
  _i3.$RecipeSharesTable get recipeShares => (super.noSuchMethod(
        Invocation.getter(#recipeShares),
        returnValue: _Fake$RecipeSharesTable_3(
          this,
          Invocation.getter(#recipeShares),
        ),
      ) as _i3.$RecipeSharesTable);

  @override
  _i3.$HouseholdMembersTable get householdMembers => (super.noSuchMethod(
        Invocation.getter(#householdMembers),
        returnValue: _Fake$HouseholdMembersTable_4(
          this,
          Invocation.getter(#householdMembers),
        ),
      ) as _i3.$HouseholdMembersTable);

  @override
  _i3.$HouseholdsTable get households => (super.noSuchMethod(
        Invocation.getter(#households),
        returnValue: _Fake$HouseholdsTable_5(
          this,
          Invocation.getter(#households),
        ),
      ) as _i3.$HouseholdsTable);

  @override
  _i3.$HouseholdInvitesTable get householdInvites => (super.noSuchMethod(
        Invocation.getter(#householdInvites),
        returnValue: _Fake$HouseholdInvitesTable_6(
          this,
          Invocation.getter(#householdInvites),
        ),
      ) as _i3.$HouseholdInvitesTable);

  @override
  _i3.$UploadQueuesTable get uploadQueues => (super.noSuchMethod(
        Invocation.getter(#uploadQueues),
        returnValue: _Fake$UploadQueuesTable_7(
          this,
          Invocation.getter(#uploadQueues),
        ),
      ) as _i3.$UploadQueuesTable);

  @override
  _i3.$IngredientTermQueuesTable get ingredientTermQueues =>
      (super.noSuchMethod(
        Invocation.getter(#ingredientTermQueues),
        returnValue: _Fake$IngredientTermQueuesTable_8(
          this,
          Invocation.getter(#ingredientTermQueues),
        ),
      ) as _i3.$IngredientTermQueuesTable);

  @override
  _i3.$PantryItemTermQueuesTable get pantryItemTermQueues =>
      (super.noSuchMethod(
        Invocation.getter(#pantryItemTermQueues),
        returnValue: _Fake$PantryItemTermQueuesTable_9(
          this,
          Invocation.getter(#pantryItemTermQueues),
        ),
      ) as _i3.$PantryItemTermQueuesTable);

  @override
  _i3.$ShoppingListItemTermQueuesTable get shoppingListItemTermQueues =>
      (super.noSuchMethod(
        Invocation.getter(#shoppingListItemTermQueues),
        returnValue: _Fake$ShoppingListItemTermQueuesTable_10(
          this,
          Invocation.getter(#shoppingListItemTermQueues),
        ),
      ) as _i3.$ShoppingListItemTermQueuesTable);

  @override
  _i3.$CooksTable get cooks => (super.noSuchMethod(
        Invocation.getter(#cooks),
        returnValue: _Fake$CooksTable_11(
          this,
          Invocation.getter(#cooks),
        ),
      ) as _i3.$CooksTable);

  @override
  _i3.$PantryItemsTable get pantryItems => (super.noSuchMethod(
        Invocation.getter(#pantryItems),
        returnValue: _Fake$PantryItemsTable_12(
          this,
          Invocation.getter(#pantryItems),
        ),
      ) as _i3.$PantryItemsTable);

  @override
  _i3.$IngredientTermOverridesTable get ingredientTermOverrides =>
      (super.noSuchMethod(
        Invocation.getter(#ingredientTermOverrides),
        returnValue: _Fake$IngredientTermOverridesTable_13(
          this,
          Invocation.getter(#ingredientTermOverrides),
        ),
      ) as _i3.$IngredientTermOverridesTable);

  @override
  _i3.$ShoppingListItemsTable get shoppingListItems => (super.noSuchMethod(
        Invocation.getter(#shoppingListItems),
        returnValue: _Fake$ShoppingListItemsTable_14(
          this,
          Invocation.getter(#shoppingListItems),
        ),
      ) as _i3.$ShoppingListItemsTable);

  @override
  _i3.$ShoppingListsTable get shoppingLists => (super.noSuchMethod(
        Invocation.getter(#shoppingLists),
        returnValue: _Fake$ShoppingListsTable_15(
          this,
          Invocation.getter(#shoppingLists),
        ),
      ) as _i3.$ShoppingListsTable);

  @override
  _i3.$ConvertersTable get converters => (super.noSuchMethod(
        Invocation.getter(#converters),
        returnValue: _Fake$ConvertersTable_16(
          this,
          Invocation.getter(#converters),
        ),
      ) as _i3.$ConvertersTable);

  @override
  _i3.$MealPlansTable get mealPlans => (super.noSuchMethod(
        Invocation.getter(#mealPlans),
        returnValue: _Fake$MealPlansTable_17(
          this,
          Invocation.getter(#mealPlans),
        ),
      ) as _i3.$MealPlansTable);

  @override
  _i3.$AppDatabaseManager get managers => (super.noSuchMethod(
        Invocation.getter(#managers),
        returnValue: _Fake$AppDatabaseManager_18(
          this,
          Invocation.getter(#managers),
        ),
      ) as _i3.$AppDatabaseManager);

  @override
  Iterable<_i4.TableInfo<_i4.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i4.TableInfo<_i4.Table, Object?>>[],
      ) as Iterable<_i4.TableInfo<_i4.Table, Object?>>);

  @override
  List<_i4.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i4.DatabaseSchemaEntity>[],
      ) as List<_i4.DatabaseSchemaEntity>);

  @override
  _i4.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_19(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i4.GeneratedDatabase);

  @override
  _i4.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_20(
          this,
          Invocation.getter(#options),
        ),
      ) as _i4.DriftDatabaseOptions);

  @override
  _i4.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_21(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i4.MigrationStrategy);

  @override
  _i4.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_22(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i4.StreamQueryUpdateRules);

  @override
  _i4.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_23(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i4.DatabaseConnection);

  @override
  _i4.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i10.dummyValue<_i4.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i4.SqlTypes);

  @override
  _i4.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_24(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i4.QueryExecutor);

  @override
  _i5.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_25(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i5.StreamQueryStore);

  @override
  _i4.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_26(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i4.DatabaseConnectionUser);

  @override
  _i4.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(
          #createMigrator,
          [],
        ),
        returnValue: _FakeMigrator_27(
          this,
          Invocation.method(
            #createMigrator,
            [],
          ),
        ),
      ) as _i4.Migrator);

  @override
  _i6.Future<void> beforeOpen(
    _i4.QueryExecutor? executor,
    _i4.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #beforeOpen,
          [
            executor,
            details,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<T> createStream<T extends Object>(
          _i5.QueryStreamFetcher<T>? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i6.Stream<T>.empty(),
      ) as _i6.Stream<T>);

  @override
  T alias<T, D>(
    _i4.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i10.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i4.TableInfo<_i4.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i4.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Stream<Set<_i4.TableUpdate>> tableUpdates(
          [_i4.TableUpdateQuery? query = const _i4.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i6.Stream<Set<_i4.TableUpdate>>.empty(),
      ) as _i6.Stream<Set<_i4.TableUpdate>>);

  @override
  _i6.Future<T> doWhenOpened<T>(
          _i6.FutureOr<T> Function(_i4.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i6.Future<T>.value(v),
            ) ??
            _FakeFuture_28<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i6.Future<T>);

  @override
  _i4.InsertStatement<T, D> into<T extends _i4.Table, D>(
          _i4.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_29<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i4.InsertStatement<T, D>);

  @override
  _i4.UpdateStatement<Tbl, R> update<Tbl extends _i4.Table, R>(
          _i4.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_30<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i4.UpdateStatement<Tbl, R>);

  @override
  _i4.SimpleSelectStatement<T, R> select<T extends _i4.HasResultSet, R>(
    _i4.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_31<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i4.SimpleSelectStatement<T, R>);

  @override
  _i4.JoinedSelectStatement<T, R> selectOnly<T extends _i4.HasResultSet, R>(
    _i4.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_32<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i4.JoinedSelectStatement<T, R>);

  @override
  _i4.BaseSelectStatement<_i4.TypedResult> selectExpressions(
          Iterable<_i4.Expression<Object>>? columns) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectExpressions,
          [columns],
        ),
        returnValue: _FakeBaseSelectStatement_33<_i4.TypedResult>(
          this,
          Invocation.method(
            #selectExpressions,
            [columns],
          ),
        ),
      ) as _i4.BaseSelectStatement<_i4.TypedResult>);

  @override
  _i4.DeleteStatement<T, D> delete<T extends _i4.Table, D>(
          _i4.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_34<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i4.DeleteStatement<T, D>);

  @override
  _i6.Future<int> customUpdate(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i4.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> customInsert(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i4.QueryRow>> customWriteReturning(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i4.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i6.Future<List<_i4.QueryRow>>.value(<_i4.QueryRow>[]),
      ) as _i6.Future<List<_i4.QueryRow>>);

  @override
  _i4.Selectable<_i4.QueryRow> customSelect(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_35<_i4.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i4.Selectable<_i4.QueryRow>);

  @override
  _i4.Selectable<_i4.QueryRow> customSelectQuery(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_35<_i4.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i4.Selectable<_i4.QueryRow>);

  @override
  _i6.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<T> transaction<T>(
    _i6.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i6.Future<T>.value(v),
            ) ??
            _FakeFuture_28<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i6.Future<T>);

  @override
  _i6.Future<T> exclusively<T>(_i6.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #exclusively,
          [action],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #exclusively,
                  [action],
                ),
              ),
              (T v) => _i6.Future<T>.value(v),
            ) ??
            _FakeFuture_28<T>(
              this,
              Invocation.method(
                #exclusively,
                [action],
              ),
            ),
      ) as _i6.Future<T>);

  @override
  _i6.Future<void> batch(_i6.FutureOr<void> Function(_i4.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<T> runWithInterceptor<T>(
    _i6.Future<T> Function()? action, {
    required _i4.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runWithInterceptor,
          [action],
          {#interceptor: interceptor},
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #runWithInterceptor,
                  [action],
                  {#interceptor: interceptor},
                ),
              ),
              (T v) => _i6.Future<T>.value(v),
            ) ??
            _FakeFuture_28<T>(
              this,
              Invocation.method(
                #runWithInterceptor,
                [action],
                {#interceptor: interceptor},
              ),
            ),
      ) as _i6.Future<T>);

  @override
  _i4.GenerationContext $write(
    _i4.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_36(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i4.GenerationContext);

  @override
  _i4.GenerationContext $writeInsertable(
    _i4.TableInfo<_i4.Table, dynamic>? table,
    _i4.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_36(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i4.GenerationContext);

  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #$expandVar,
            [
              start,
              amount,
            ],
          ),
        ),
      ) as String);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i7.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.FunctionsClient get functions => (super.noSuchMethod(
        Invocation.getter(#functions),
        returnValue: _FakeFunctionsClient_37(
          this,
          Invocation.getter(#functions),
        ),
      ) as _i7.FunctionsClient);

  @override
  set functions(_i7.FunctionsClient? _functions) => super.noSuchMethod(
        Invocation.setter(
          #functions,
          _functions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.SupabaseStorageClient get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeSupabaseStorageClient_38(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i7.SupabaseStorageClient);

  @override
  set storage(_i7.SupabaseStorageClient? _storage) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          _storage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.RealtimeClient get realtime => (super.noSuchMethod(
        Invocation.getter(#realtime),
        returnValue: _FakeRealtimeClient_39(
          this,
          Invocation.getter(#realtime),
        ),
      ) as _i7.RealtimeClient);

  @override
  set realtime(_i7.RealtimeClient? _realtime) => super.noSuchMethod(
        Invocation.setter(
          #realtime,
          _realtime,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.PostgrestClient get rest => (super.noSuchMethod(
        Invocation.getter(#rest),
        returnValue: _FakePostgrestClient_40(
          this,
          Invocation.getter(#rest),
        ),
      ) as _i7.PostgrestClient);

  @override
  set rest(_i7.PostgrestClient? _rest) => super.noSuchMethod(
        Invocation.setter(
          #rest,
          _rest,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
        Invocation.setter(
          #headers,
          headers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.GoTrueClient get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeGoTrueClient_41(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i7.GoTrueClient);

  @override
  _i7.SupabaseQueryBuilder from(String? table) => (super.noSuchMethod(
        Invocation.method(
          #from,
          [table],
        ),
        returnValue: _FakeSupabaseQueryBuilder_42(
          this,
          Invocation.method(
            #from,
            [table],
          ),
        ),
      ) as _i7.SupabaseQueryBuilder);

  @override
  _i7.SupabaseQuerySchema schema(String? schema) => (super.noSuchMethod(
        Invocation.method(
          #schema,
          [schema],
        ),
        returnValue: _FakeSupabaseQuerySchema_43(
          this,
          Invocation.method(
            #schema,
            [schema],
          ),
        ),
      ) as _i7.SupabaseQuerySchema);

  @override
  _i7.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rpc,
          [fn],
          {
            #params: params,
            #get: get,
          },
        ),
        returnValue: _FakePostgrestFilterBuilder_44<T>(
          this,
          Invocation.method(
            #rpc,
            [fn],
            {
              #params: params,
              #get: get,
            },
          ),
        ),
      ) as _i7.PostgrestFilterBuilder<T>);

  @override
  _i7.RealtimeChannel channel(
    String? name, {
    _i7.RealtimeChannelConfig? opts = const _i7.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #channel,
          [name],
          {#opts: opts},
        ),
        returnValue: _FakeRealtimeChannel_45(
          this,
          Invocation.method(
            #channel,
            [name],
            {#opts: opts},
          ),
        ),
      ) as _i7.RealtimeChannel);

  @override
  List<_i7.RealtimeChannel> getChannels() => (super.noSuchMethod(
        Invocation.method(
          #getChannels,
          [],
        ),
        returnValue: <_i7.RealtimeChannel>[],
      ) as List<_i7.RealtimeChannel>);

  @override
  _i6.Future<String> removeChannel(_i7.RealtimeChannel? channel) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeChannel,
          [channel],
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #removeChannel,
            [channel],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<List<String>> removeAllChannels() => (super.noSuchMethod(
        Invocation.method(
          #removeAllChannels,
          [],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [GoTrueClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoTrueClient extends _i1.Mock implements _i7.GoTrueClient {
  MockGoTrueClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.GoTrueAdminApi get admin => (super.noSuchMethod(
        Invocation.getter(#admin),
        returnValue: _FakeGoTrueAdminApi_46(
          this,
          Invocation.getter(#admin),
        ),
      ) as _i7.GoTrueAdminApi);

  @override
  set admin(_i7.GoTrueAdminApi? _admin) => super.noSuchMethod(
        Invocation.setter(
          #admin,
          _admin,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.GoTrueMFAApi get mfa => (super.noSuchMethod(
        Invocation.getter(#mfa),
        returnValue: _FakeGoTrueMFAApi_47(
          this,
          Invocation.getter(#mfa),
        ),
      ) as _i7.GoTrueMFAApi);

  @override
  set mfa(_i7.GoTrueMFAApi? _mfa) => super.noSuchMethod(
        Invocation.setter(
          #mfa,
          _mfa,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Stream<_i7.AuthState> get onAuthStateChange => (super.noSuchMethod(
        Invocation.getter(#onAuthStateChange),
        returnValue: _i6.Stream<_i7.AuthState>.empty(),
      ) as _i6.Stream<_i7.AuthState>);

  @override
  _i6.Stream<_i7.AuthState> get onAuthStateChangeSync => (super.noSuchMethod(
        Invocation.getter(#onAuthStateChangeSync),
        returnValue: _i6.Stream<_i7.AuthState>.empty(),
      ) as _i6.Stream<_i7.AuthState>);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i6.Future<_i7.AuthResponse> signInAnonymously({
    Map<String, dynamic>? data,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
          {
            #data: data,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i6.Future<_i7.AuthResponse>.value(_FakeAuthResponse_48(
          this,
          Invocation.method(
            #signInAnonymously,
            [],
            {
              #data: data,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i6.Future<_i7.AuthResponse>);

  @override
  _i6.Future<_i7.AuthResponse> signUp({
    String? email,
    String? phone,
    required String? password,
    String? emailRedirectTo,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i7.OtpChannel? channel = _i7.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #phone: phone,
            #password: password,
            #emailRedirectTo: emailRedirectTo,
            #data: data,
            #captchaToken: captchaToken,
            #channel: channel,
          },
        ),
        returnValue: _i6.Future<_i7.AuthResponse>.value(_FakeAuthResponse_48(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
              #emailRedirectTo: emailRedirectTo,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            },
          ),
        )),
      ) as _i6.Future<_i7.AuthResponse>);

  @override
  _i6.Future<_i7.AuthResponse> signInWithPassword({
    String? email,
    String? phone,
    required String? password,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithPassword,
          [],
          {
            #email: email,
            #phone: phone,
            #password: password,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i6.Future<_i7.AuthResponse>.value(_FakeAuthResponse_48(
          this,
          Invocation.method(
            #signInWithPassword,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i6.Future<_i7.AuthResponse>);

  @override
  _i6.Future<_i7.OAuthResponse> getOAuthSignInUrl({
    required _i7.OAuthProvider? provider,
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOAuthSignInUrl,
          [],
          {
            #provider: provider,
            #redirectTo: redirectTo,
            #scopes: scopes,
            #queryParams: queryParams,
          },
        ),
        returnValue: _i6.Future<_i7.OAuthResponse>.value(_FakeOAuthResponse_49(
          this,
          Invocation.method(
            #getOAuthSignInUrl,
            [],
            {
              #provider: provider,
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            },
          ),
        )),
      ) as _i6.Future<_i7.OAuthResponse>);

  @override
  _i6.Future<_i7.AuthSessionUrlResponse> exchangeCodeForSession(
          String? authCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #exchangeCodeForSession,
          [authCode],
        ),
        returnValue: _i6.Future<_i7.AuthSessionUrlResponse>.value(
            _FakeAuthSessionUrlResponse_50(
          this,
          Invocation.method(
            #exchangeCodeForSession,
            [authCode],
          ),
        )),
      ) as _i6.Future<_i7.AuthSessionUrlResponse>);

  @override
  _i6.Future<_i7.AuthResponse> signInWithIdToken({
    required _i7.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithIdToken,
          [],
          {
            #provider: provider,
            #idToken: idToken,
            #accessToken: accessToken,
            #nonce: nonce,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i6.Future<_i7.AuthResponse>.value(_FakeAuthResponse_48(
          this,
          Invocation.method(
            #signInWithIdToken,
            [],
            {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i6.Future<_i7.AuthResponse>);

  @override
  _i6.Future<void> signInWithOtp({
    String? email,
    String? phone,
    String? emailRedirectTo,
    bool? shouldCreateUser,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i7.OtpChannel? channel = _i7.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithOtp,
          [],
          {
            #email: email,
            #phone: phone,
            #emailRedirectTo: emailRedirectTo,
            #shouldCreateUser: shouldCreateUser,
            #data: data,
            #captchaToken: captchaToken,
            #channel: channel,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.AuthResponse> verifyOTP({
    String? email,
    String? phone,
    String? token,
    required _i7.OtpType? type,
    String? redirectTo,
    String? captchaToken,
    String? tokenHash,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOTP,
          [],
          {
            #email: email,
            #phone: phone,
            #token: token,
            #type: type,
            #redirectTo: redirectTo,
            #captchaToken: captchaToken,
            #tokenHash: tokenHash,
          },
        ),
        returnValue: _i6.Future<_i7.AuthResponse>.value(_FakeAuthResponse_48(
          this,
          Invocation.method(
            #verifyOTP,
            [],
            {
              #email: email,
              #phone: phone,
              #token: token,
              #type: type,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
              #tokenHash: tokenHash,
            },
          ),
        )),
      ) as _i6.Future<_i7.AuthResponse>);

  @override
  _i6.Future<String> getSSOSignInUrl({
    String? providerId,
    String? domain,
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSSOSignInUrl,
          [],
          {
            #providerId: providerId,
            #domain: domain,
            #redirectTo: redirectTo,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #getSSOSignInUrl,
            [],
            {
              #providerId: providerId,
              #domain: domain,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i7.AuthResponse> refreshSession([String? refreshToken]) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshSession,
          [refreshToken],
        ),
        returnValue: _i6.Future<_i7.AuthResponse>.value(_FakeAuthResponse_48(
          this,
          Invocation.method(
            #refreshSession,
            [refreshToken],
          ),
        )),
      ) as _i6.Future<_i7.AuthResponse>);

  @override
  _i6.Future<void> reauthenticate() => (super.noSuchMethod(
        Invocation.method(
          #reauthenticate,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.ResendResponse> resend({
    String? email,
    String? phone,
    required _i7.OtpType? type,
    String? emailRedirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resend,
          [],
          {
            #email: email,
            #phone: phone,
            #type: type,
            #emailRedirectTo: emailRedirectTo,
            #captchaToken: captchaToken,
          },
        ),
        returnValue:
            _i6.Future<_i7.ResendResponse>.value(_FakeResendResponse_51(
          this,
          Invocation.method(
            #resend,
            [],
            {
              #email: email,
              #phone: phone,
              #type: type,
              #emailRedirectTo: emailRedirectTo,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i6.Future<_i7.ResendResponse>);

  @override
  _i6.Future<_i7.UserResponse> getUser([String? jwt]) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [jwt],
        ),
        returnValue: _i6.Future<_i7.UserResponse>.value(_FakeUserResponse_52(
          this,
          Invocation.method(
            #getUser,
            [jwt],
          ),
        )),
      ) as _i6.Future<_i7.UserResponse>);

  @override
  _i6.Future<_i7.UserResponse> updateUser(
    _i7.UserAttributes? attributes, {
    String? emailRedirectTo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [attributes],
          {#emailRedirectTo: emailRedirectTo},
        ),
        returnValue: _i6.Future<_i7.UserResponse>.value(_FakeUserResponse_52(
          this,
          Invocation.method(
            #updateUser,
            [attributes],
            {#emailRedirectTo: emailRedirectTo},
          ),
        )),
      ) as _i6.Future<_i7.UserResponse>);

  @override
  _i6.Future<_i7.AuthResponse> setSession(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSession,
          [refreshToken],
        ),
        returnValue: _i6.Future<_i7.AuthResponse>.value(_FakeAuthResponse_48(
          this,
          Invocation.method(
            #setSession,
            [refreshToken],
          ),
        )),
      ) as _i6.Future<_i7.AuthResponse>);

  @override
  _i6.Future<_i7.AuthSessionUrlResponse> getSessionFromUrl(
    Uri? originUrl, {
    bool? storeSession = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionFromUrl,
          [originUrl],
          {#storeSession: storeSession},
        ),
        returnValue: _i6.Future<_i7.AuthSessionUrlResponse>.value(
            _FakeAuthSessionUrlResponse_50(
          this,
          Invocation.method(
            #getSessionFromUrl,
            [originUrl],
            {#storeSession: storeSession},
          ),
        )),
      ) as _i6.Future<_i7.AuthSessionUrlResponse>);

  @override
  _i6.Future<void> signOut(
          {_i7.SignOutScope? scope = _i7.SignOutScope.local}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
          {#scope: scope},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resetPasswordForEmail(
    String? email, {
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPasswordForEmail,
          [email],
          {
            #redirectTo: redirectTo,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.UserIdentity>> getUserIdentities() => (super.noSuchMethod(
        Invocation.method(
          #getUserIdentities,
          [],
        ),
        returnValue:
            _i6.Future<List<_i7.UserIdentity>>.value(<_i7.UserIdentity>[]),
      ) as _i6.Future<List<_i7.UserIdentity>>);

  @override
  _i6.Future<_i7.OAuthResponse> getLinkIdentityUrl(
    _i7.OAuthProvider? provider, {
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLinkIdentityUrl,
          [provider],
          {
            #redirectTo: redirectTo,
            #scopes: scopes,
            #queryParams: queryParams,
          },
        ),
        returnValue: _i6.Future<_i7.OAuthResponse>.value(_FakeOAuthResponse_49(
          this,
          Invocation.method(
            #getLinkIdentityUrl,
            [provider],
            {
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            },
          ),
        )),
      ) as _i6.Future<_i7.OAuthResponse>);

  @override
  _i6.Future<void> unlinkIdentity(_i7.UserIdentity? identity) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlinkIdentity,
          [identity],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setInitialSession(String? jsonStr) => (super.noSuchMethod(
        Invocation.method(
          #setInitialSession,
          [jsonStr],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.AuthResponse> recoverSession(String? jsonStr) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverSession,
          [jsonStr],
        ),
        returnValue: _i6.Future<_i7.AuthResponse>.value(_FakeAuthResponse_48(
          this,
          Invocation.method(
            #recoverSession,
            [jsonStr],
          ),
        )),
      ) as _i6.Future<_i7.AuthResponse>);

  @override
  void startAutoRefresh() => super.noSuchMethod(
        Invocation.method(
          #startAutoRefresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopAutoRefresh() => super.noSuchMethod(
        Invocation.method(
          #stopAutoRefresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyAllSubscribers(
    _i7.AuthChangeEvent? event, {
    _i7.Session? session,
    bool? broadcast = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #notifyAllSubscribers,
          [event],
          {
            #session: session,
            #broadcast: broadcast,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  Object notifyException(
    Object? exception, [
    StackTrace? stackTrace,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyException,
          [
            exception,
            stackTrace,
          ],
        ),
        returnValue: _FakeObject_53(
          this,
          Invocation.method(
            #notifyException,
            [
              exception,
              stackTrace,
            ],
          ),
        ),
      ) as Object);
}

/// A class which mocks [SupabaseStorageClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseStorageClient extends _i1.Mock
    implements _i7.SupabaseStorageClient {
  MockSupabaseStorageClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i8.Fetch get storageFetch => (super.noSuchMethod(
        Invocation.getter(#storageFetch),
        returnValue: _FakeFetch_54(
          this,
          Invocation.getter(#storageFetch),
        ),
      ) as _i8.Fetch);

  @override
  set storageFetch(_i8.Fetch? _storageFetch) => super.noSuchMethod(
        Invocation.setter(
          #storageFetch,
          _storageFetch,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.StorageFileApi from(String? id) => (super.noSuchMethod(
        Invocation.method(
          #from,
          [id],
        ),
        returnValue: _FakeStorageFileApi_55(
          this,
          Invocation.method(
            #from,
            [id],
          ),
        ),
      ) as _i7.StorageFileApi);

  @override
  void setAuth(String? jwt) => super.noSuchMethod(
        Invocation.method(
          #setAuth,
          [jwt],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<List<_i7.Bucket>> listBuckets() => (super.noSuchMethod(
        Invocation.method(
          #listBuckets,
          [],
        ),
        returnValue: _i6.Future<List<_i7.Bucket>>.value(<_i7.Bucket>[]),
      ) as _i6.Future<List<_i7.Bucket>>);

  @override
  _i6.Future<_i7.Bucket> getBucket(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getBucket,
          [id],
        ),
        returnValue: _i6.Future<_i7.Bucket>.value(_FakeBucket_56(
          this,
          Invocation.method(
            #getBucket,
            [id],
          ),
        )),
      ) as _i6.Future<_i7.Bucket>);

  @override
  _i6.Future<String> createBucket(
    String? id, [
    _i7.BucketOptions? bucketOptions = const _i7.BucketOptions(public: false),
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBucket,
          [
            id,
            bucketOptions,
          ],
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #createBucket,
            [
              id,
              bucketOptions,
            ],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> updateBucket(
    String? id,
    _i7.BucketOptions? bucketOptions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBucket,
          [
            id,
            bucketOptions,
          ],
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #updateBucket,
            [
              id,
              bucketOptions,
            ],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> emptyBucket(String? id) => (super.noSuchMethod(
        Invocation.method(
          #emptyBucket,
          [id],
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #emptyBucket,
            [id],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> deleteBucket(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBucket,
          [id],
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #deleteBucket,
            [id],
          ),
        )),
      ) as _i6.Future<String>);
}

/// A class which mocks [StorageFileApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageFileApi extends _i1.Mock implements _i7.StorageFileApi {
  MockStorageFileApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i6.Future<String> upload(
    String? path,
    _i17.File? file, {
    _i7.FileOptions? fileOptions = const _i7.FileOptions(),
    int? retryAttempts,
    _i7.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upload,
          [
            path,
            file,
          ],
          {
            #fileOptions: fileOptions,
            #retryAttempts: retryAttempts,
            #retryController: retryController,
          },
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #upload,
            [
              path,
              file,
            ],
            {
              #fileOptions: fileOptions,
              #retryAttempts: retryAttempts,
              #retryController: retryController,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> uploadBinary(
    String? path,
    _i18.Uint8List? data, {
    _i7.FileOptions? fileOptions = const _i7.FileOptions(),
    int? retryAttempts,
    _i7.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBinary,
          [
            path,
            data,
          ],
          {
            #fileOptions: fileOptions,
            #retryAttempts: retryAttempts,
            #retryController: retryController,
          },
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #uploadBinary,
            [
              path,
              data,
            ],
            {
              #fileOptions: fileOptions,
              #retryAttempts: retryAttempts,
              #retryController: retryController,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> uploadToSignedUrl(
    String? path,
    String? token,
    _i17.File? file, [
    _i7.FileOptions? fileOptions = const _i7.FileOptions(),
    int? retryAttempts,
    _i7.StorageRetryController? retryController,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadToSignedUrl,
          [
            path,
            token,
            file,
            fileOptions,
            retryAttempts,
            retryController,
          ],
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #uploadToSignedUrl,
            [
              path,
              token,
              file,
              fileOptions,
              retryAttempts,
              retryController,
            ],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> uploadBinaryToSignedUrl(
    String? path,
    String? token,
    _i18.Uint8List? data, [
    _i7.FileOptions? fileOptions = const _i7.FileOptions(),
    int? retryAttempts,
    _i7.StorageRetryController? retryController,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBinaryToSignedUrl,
          [
            path,
            token,
            data,
            fileOptions,
            retryAttempts,
            retryController,
          ],
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #uploadBinaryToSignedUrl,
            [
              path,
              token,
              data,
              fileOptions,
              retryAttempts,
              retryController,
            ],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i7.SignedUploadURLResponse> createSignedUploadUrl(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSignedUploadUrl,
          [path],
        ),
        returnValue: _i6.Future<_i7.SignedUploadURLResponse>.value(
            _FakeSignedUploadURLResponse_57(
          this,
          Invocation.method(
            #createSignedUploadUrl,
            [path],
          ),
        )),
      ) as _i6.Future<_i7.SignedUploadURLResponse>);

  @override
  _i6.Future<String> update(
    String? path,
    _i17.File? file, {
    _i7.FileOptions? fileOptions = const _i7.FileOptions(),
    int? retryAttempts,
    _i7.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            path,
            file,
          ],
          {
            #fileOptions: fileOptions,
            #retryAttempts: retryAttempts,
            #retryController: retryController,
          },
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #update,
            [
              path,
              file,
            ],
            {
              #fileOptions: fileOptions,
              #retryAttempts: retryAttempts,
              #retryController: retryController,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> updateBinary(
    String? path,
    _i18.Uint8List? data, {
    _i7.FileOptions? fileOptions = const _i7.FileOptions(),
    int? retryAttempts,
    _i7.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBinary,
          [
            path,
            data,
          ],
          {
            #fileOptions: fileOptions,
            #retryAttempts: retryAttempts,
            #retryController: retryController,
          },
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #updateBinary,
            [
              path,
              data,
            ],
            {
              #fileOptions: fileOptions,
              #retryAttempts: retryAttempts,
              #retryController: retryController,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> move(
    String? fromPath,
    String? toPath, {
    String? destinationBucket,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #move,
          [
            fromPath,
            toPath,
          ],
          {#destinationBucket: destinationBucket},
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #move,
            [
              fromPath,
              toPath,
            ],
            {#destinationBucket: destinationBucket},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> copy(
    String? fromPath,
    String? toPath, {
    String? destinationBucket,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copy,
          [
            fromPath,
            toPath,
          ],
          {#destinationBucket: destinationBucket},
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #copy,
            [
              fromPath,
              toPath,
            ],
            {#destinationBucket: destinationBucket},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> createSignedUrl(
    String? path,
    int? expiresIn, {
    _i7.TransformOptions? transform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSignedUrl,
          [
            path,
            expiresIn,
          ],
          {#transform: transform},
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #createSignedUrl,
            [
              path,
              expiresIn,
            ],
            {#transform: transform},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<List<_i7.SignedUrl>> createSignedUrls(
    List<String>? paths,
    int? expiresIn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSignedUrls,
          [
            paths,
            expiresIn,
          ],
        ),
        returnValue: _i6.Future<List<_i7.SignedUrl>>.value(<_i7.SignedUrl>[]),
      ) as _i6.Future<List<_i7.SignedUrl>>);

  @override
  _i6.Future<_i18.Uint8List> download(
    String? path, {
    _i7.TransformOptions? transform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [path],
          {#transform: transform},
        ),
        returnValue: _i6.Future<_i18.Uint8List>.value(_i18.Uint8List(0)),
      ) as _i6.Future<_i18.Uint8List>);

  @override
  String getPublicUrl(
    String? path, {
    _i7.TransformOptions? transform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicUrl,
          [path],
          {#transform: transform},
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #getPublicUrl,
            [path],
            {#transform: transform},
          ),
        ),
      ) as String);

  @override
  _i6.Future<List<_i7.FileObject>> remove(List<String>? paths) =>
      (super.noSuchMethod(
        Invocation.method(
          #remove,
          [paths],
        ),
        returnValue: _i6.Future<List<_i7.FileObject>>.value(<_i7.FileObject>[]),
      ) as _i6.Future<List<_i7.FileObject>>);

  @override
  _i6.Future<List<_i7.FileObject>> list({
    String? path,
    _i7.SearchOptions? searchOptions = const _i7.SearchOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #list,
          [],
          {
            #path: path,
            #searchOptions: searchOptions,
          },
        ),
        returnValue: _i6.Future<List<_i7.FileObject>>.value(<_i7.FileObject>[]),
      ) as _i6.Future<List<_i7.FileObject>>);
}
