// Mocks generated by Mockito 5.4.5 from annotations
// in recipe_app/test/unit/upload_queue_manager.test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i14;
import 'dart:typed_data' as _i15;

import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:recipe_app/database/database.dart' as _i2;
import 'package:recipe_app/database/models/ingredients.dart' as _i11;
import 'package:recipe_app/database/models/steps.dart' as _i12;
import 'package:recipe_app/src/models/recipe_with_folders.dart' as _i13;
import 'package:recipe_app/src/repositories/recipe_repository.dart' as _i10;
import 'package:recipe_app/src/repositories/upload_queue_repository.dart'
    as _i8;
import 'package:storage_client/src/fetch.dart' as _i7;
import 'package:supabase/supabase.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _Fake$RecipeFoldersTable_0 extends _i1.SmartFake
    implements _i2.$RecipeFoldersTable {
  _Fake$RecipeFoldersTable_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$RecipesTable_1 extends _i1.SmartFake implements _i2.$RecipesTable {
  _Fake$RecipesTable_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$RecipeSharesTable_2 extends _i1.SmartFake
    implements _i2.$RecipeSharesTable {
  _Fake$RecipeSharesTable_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$HouseholdMembersTable_3 extends _i1.SmartFake
    implements _i2.$HouseholdMembersTable {
  _Fake$HouseholdMembersTable_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$HouseholdsTable_4 extends _i1.SmartFake
    implements _i2.$HouseholdsTable {
  _Fake$HouseholdsTable_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$UploadQueuesTable_5 extends _i1.SmartFake
    implements _i2.$UploadQueuesTable {
  _Fake$UploadQueuesTable_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$CooksTable_6 extends _i1.SmartFake implements _i2.$CooksTable {
  _Fake$CooksTable_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$PantryItemsTable_7 extends _i1.SmartFake
    implements _i2.$PantryItemsTable {
  _Fake$PantryItemsTable_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$IngredientTermOverridesTable_8 extends _i1.SmartFake
    implements _i2.$IngredientTermOverridesTable {
  _Fake$IngredientTermOverridesTable_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ShoppingListItemsTable_9 extends _i1.SmartFake
    implements _i2.$ShoppingListItemsTable {
  _Fake$ShoppingListItemsTable_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ShoppingListsTable_10 extends _i1.SmartFake
    implements _i2.$ShoppingListsTable {
  _Fake$ShoppingListsTable_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AppDatabaseManager_11 extends _i1.SmartFake
    implements _i2.$AppDatabaseManager {
  _Fake$AppDatabaseManager_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedDatabase_12 extends _i1.SmartFake
    implements _i3.GeneratedDatabase {
  _FakeGeneratedDatabase_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_13 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrationStrategy_14 extends _i1.SmartFake
    implements _i3.MigrationStrategy {
  _FakeMigrationStrategy_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryUpdateRules_15 extends _i1.SmartFake
    implements _i3.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_16 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_17 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_18 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_19 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrator_20 extends _i1.SmartFake implements _i3.Migrator {
  _FakeMigrator_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_21<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_22<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_23<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_24<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_25<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseSelectStatement_26<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_27<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_28<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_29 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFunctionsClient_30 extends _i1.SmartFake
    implements _i6.FunctionsClient {
  _FakeFunctionsClient_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseStorageClient_31 extends _i1.SmartFake
    implements _i6.SupabaseStorageClient {
  _FakeSupabaseStorageClient_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeClient_32 extends _i1.SmartFake
    implements _i6.RealtimeClient {
  _FakeRealtimeClient_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestClient_33 extends _i1.SmartFake
    implements _i6.PostgrestClient {
  _FakePostgrestClient_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueClient_34 extends _i1.SmartFake implements _i6.GoTrueClient {
  _FakeGoTrueClient_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQueryBuilder_35 extends _i1.SmartFake
    implements _i6.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQuerySchema_36 extends _i1.SmartFake
    implements _i6.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestFilterBuilder_37<T1> extends _i1.SmartFake
    implements _i6.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_37(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeChannel_38 extends _i1.SmartFake
    implements _i6.RealtimeChannel {
  _FakeRealtimeChannel_38(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueAdminApi_39 extends _i1.SmartFake
    implements _i6.GoTrueAdminApi {
  _FakeGoTrueAdminApi_39(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueMFAApi_40 extends _i1.SmartFake implements _i6.GoTrueMFAApi {
  _FakeGoTrueMFAApi_40(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResponse_41 extends _i1.SmartFake implements _i6.AuthResponse {
  _FakeAuthResponse_41(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOAuthResponse_42 extends _i1.SmartFake implements _i6.OAuthResponse {
  _FakeOAuthResponse_42(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthSessionUrlResponse_43 extends _i1.SmartFake
    implements _i6.AuthSessionUrlResponse {
  _FakeAuthSessionUrlResponse_43(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResendResponse_44 extends _i1.SmartFake
    implements _i6.ResendResponse {
  _FakeResendResponse_44(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserResponse_45 extends _i1.SmartFake implements _i6.UserResponse {
  _FakeUserResponse_45(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObject_46 extends _i1.SmartFake implements Object {
  _FakeObject_46(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFetch_47 extends _i1.SmartFake implements _i7.Fetch {
  _FakeFetch_47(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageFileApi_48 extends _i1.SmartFake
    implements _i6.StorageFileApi {
  _FakeStorageFileApi_48(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBucket_49 extends _i1.SmartFake implements _i6.Bucket {
  _FakeBucket_49(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignedUploadURLResponse_50 extends _i1.SmartFake
    implements _i6.SignedUploadURLResponse {
  _FakeSignedUploadURLResponse_50(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UploadQueueRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadQueueRepository extends _i1.Mock
    implements _i8.UploadQueueRepository {
  MockUploadQueueRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<int> insertUploadQueueEntry({
    required String? fileName,
    required String? recipeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertUploadQueueEntry,
          [],
          {
            #fileName: fileName,
            #recipeId: recipeId,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.UploadQueueEntry>> getPendingEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingEntries,
          [],
        ),
        returnValue: _i5.Future<List<_i2.UploadQueueEntry>>.value(
            <_i2.UploadQueueEntry>[]),
      ) as _i5.Future<List<_i2.UploadQueueEntry>>);

  @override
  _i5.Future<int> deleteEntryByFileName(String? fileName) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEntryByFileName,
          [fileName],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> updateEntry(_i2.UploadQueueEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [entry],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> markEntryAsUploaded(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markEntryAsUploaded,
          [id],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<String> resolveFullPath(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #resolveFullPath,
          [fileName],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #resolveFullPath,
            [fileName],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i2.UploadQueueEntry?> getEntryByFileName(String? fileName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntryByFileName,
          [fileName],
        ),
        returnValue: _i5.Future<_i2.UploadQueueEntry?>.value(),
      ) as _i5.Future<_i2.UploadQueueEntry?>);
}

/// A class which mocks [RecipeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeRepository extends _i1.Mock implements _i10.RecipeRepository {
  MockRecipeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i2.RecipeEntry>> watchAllRecipes() => (super.noSuchMethod(
        Invocation.method(
          #watchAllRecipes,
          [],
        ),
        returnValue: _i5.Stream<List<_i2.RecipeEntry>>.empty(),
      ) as _i5.Stream<List<_i2.RecipeEntry>>);

  @override
  _i5.Future<int> addRecipe(_i2.RecipesCompanion? recipe) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRecipe,
          [recipe],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> updateRecipe(_i2.RecipeEntry? recipe) => (super.noSuchMethod(
        Invocation.method(
          #updateRecipe,
          [recipe],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.RecipeEntry?> getRecipeById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getRecipeById,
          [id],
        ),
        returnValue: _i5.Future<_i2.RecipeEntry?>.value(),
      ) as _i5.Future<_i2.RecipeEntry?>);

  @override
  _i5.Future<bool> updateImageForRecipe({
    required String? recipeId,
    required String? fileName,
    required String? publicUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateImageForRecipe,
          [],
          {
            #recipeId: recipeId,
            #fileName: fileName,
            #publicUrl: publicUrl,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteRecipe(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRecipe,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> addFolderToRecipe({
    required String? recipeId,
    required String? folderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFolderToRecipe,
          [],
          {
            #recipeId: recipeId,
            #folderId: folderId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeFolderFromRecipe({
    required String? recipeId,
    required String? folderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFolderFromRecipe,
          [],
          {
            #recipeId: recipeId,
            #folderId: folderId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> updateIngredients(
    String? recipeId,
    List<_i11.Ingredient>? ingredients,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIngredients,
          [
            recipeId,
            ingredients,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateSteps(
    String? recipeId,
    List<_i12.Step>? steps,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSteps,
          [
            recipeId,
            steps,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Stream<List<_i13.RecipeWithFolders>> watchRecipesWithFolders() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRecipesWithFolders,
          [],
        ),
        returnValue: _i5.Stream<List<_i13.RecipeWithFolders>>.empty(),
      ) as _i5.Stream<List<_i13.RecipeWithFolders>>);

  @override
  _i5.Stream<List<_i13.RecipeWithFolders>> watchRecipesByFolderId(
          String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRecipesByFolderId,
          [folderId],
        ),
        returnValue: _i5.Stream<List<_i13.RecipeWithFolders>>.empty(),
      ) as _i5.Stream<List<_i13.RecipeWithFolders>>);

  @override
  _i5.Stream<_i2.RecipeEntry?> watchRecipeById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRecipeById,
          [id],
        ),
        returnValue: _i5.Stream<_i2.RecipeEntry?>.empty(),
      ) as _i5.Stream<_i2.RecipeEntry?>);

  @override
  _i5.Future<void> removeFolderIdFromAllRecipes(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFolderIdFromAllRecipes,
          [folderId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.RecipeEntry>> searchRecipes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRecipes,
          [query],
        ),
        returnValue:
            _i5.Future<List<_i2.RecipeEntry>>.value(<_i2.RecipeEntry>[]),
      ) as _i5.Future<List<_i2.RecipeEntry>>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i2.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
      ) as int);

  @override
  _i2.$RecipeFoldersTable get recipeFolders => (super.noSuchMethod(
        Invocation.getter(#recipeFolders),
        returnValue: _Fake$RecipeFoldersTable_0(
          this,
          Invocation.getter(#recipeFolders),
        ),
      ) as _i2.$RecipeFoldersTable);

  @override
  _i2.$RecipesTable get recipes => (super.noSuchMethod(
        Invocation.getter(#recipes),
        returnValue: _Fake$RecipesTable_1(
          this,
          Invocation.getter(#recipes),
        ),
      ) as _i2.$RecipesTable);

  @override
  _i2.$RecipeSharesTable get recipeShares => (super.noSuchMethod(
        Invocation.getter(#recipeShares),
        returnValue: _Fake$RecipeSharesTable_2(
          this,
          Invocation.getter(#recipeShares),
        ),
      ) as _i2.$RecipeSharesTable);

  @override
  _i2.$HouseholdMembersTable get householdMembers => (super.noSuchMethod(
        Invocation.getter(#householdMembers),
        returnValue: _Fake$HouseholdMembersTable_3(
          this,
          Invocation.getter(#householdMembers),
        ),
      ) as _i2.$HouseholdMembersTable);

  @override
  _i2.$HouseholdsTable get households => (super.noSuchMethod(
        Invocation.getter(#households),
        returnValue: _Fake$HouseholdsTable_4(
          this,
          Invocation.getter(#households),
        ),
      ) as _i2.$HouseholdsTable);

  @override
  _i2.$UploadQueuesTable get uploadQueues => (super.noSuchMethod(
        Invocation.getter(#uploadQueues),
        returnValue: _Fake$UploadQueuesTable_5(
          this,
          Invocation.getter(#uploadQueues),
        ),
      ) as _i2.$UploadQueuesTable);

  @override
  _i2.$CooksTable get cooks => (super.noSuchMethod(
        Invocation.getter(#cooks),
        returnValue: _Fake$CooksTable_6(
          this,
          Invocation.getter(#cooks),
        ),
      ) as _i2.$CooksTable);

  @override
  _i2.$PantryItemsTable get pantryItems => (super.noSuchMethod(
        Invocation.getter(#pantryItems),
        returnValue: _Fake$PantryItemsTable_7(
          this,
          Invocation.getter(#pantryItems),
        ),
      ) as _i2.$PantryItemsTable);

  @override
  _i2.$IngredientTermOverridesTable get ingredientTermOverrides =>
      (super.noSuchMethod(
        Invocation.getter(#ingredientTermOverrides),
        returnValue: _Fake$IngredientTermOverridesTable_8(
          this,
          Invocation.getter(#ingredientTermOverrides),
        ),
      ) as _i2.$IngredientTermOverridesTable);

  @override
  _i2.$ShoppingListItemsTable get shoppingListItems => (super.noSuchMethod(
        Invocation.getter(#shoppingListItems),
        returnValue: _Fake$ShoppingListItemsTable_9(
          this,
          Invocation.getter(#shoppingListItems),
        ),
      ) as _i2.$ShoppingListItemsTable);

  @override
  _i2.$ShoppingListsTable get shoppingLists => (super.noSuchMethod(
        Invocation.getter(#shoppingLists),
        returnValue: _Fake$ShoppingListsTable_10(
          this,
          Invocation.getter(#shoppingLists),
        ),
      ) as _i2.$ShoppingListsTable);

  @override
  _i2.$AppDatabaseManager get managers => (super.noSuchMethod(
        Invocation.getter(#managers),
        returnValue: _Fake$AppDatabaseManager_11(
          this,
          Invocation.getter(#managers),
        ),
      ) as _i2.$AppDatabaseManager);

  @override
  Iterable<_i3.TableInfo<_i3.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i3.TableInfo<_i3.Table, Object?>>[],
      ) as Iterable<_i3.TableInfo<_i3.Table, Object?>>);

  @override
  List<_i3.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i3.DatabaseSchemaEntity>[],
      ) as List<_i3.DatabaseSchemaEntity>);

  @override
  _i3.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_12(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i3.GeneratedDatabase);

  @override
  _i3.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_13(
          this,
          Invocation.getter(#options),
        ),
      ) as _i3.DriftDatabaseOptions);

  @override
  _i3.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_14(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i3.MigrationStrategy);

  @override
  _i3.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_15(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i3.StreamQueryUpdateRules);

  @override
  _i3.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_16(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i3.DatabaseConnection);

  @override
  _i3.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i9.dummyValue<_i3.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_17(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i3.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_18(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i4.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_19(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i3.DatabaseConnectionUser);

  @override
  _i3.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(
          #createMigrator,
          [],
        ),
        returnValue: _FakeMigrator_20(
          this,
          Invocation.method(
            #createMigrator,
            [],
          ),
        ),
      ) as _i3.Migrator);

  @override
  _i5.Future<void> beforeOpen(
    _i3.QueryExecutor? executor,
    _i3.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #beforeOpen,
          [
            executor,
            details,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
          _i4.QueryStreamFetcher<T>? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i5.Stream<T>.empty(),
      ) as _i5.Stream<T>);

  @override
  T alias<T, D>(
    _i3.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i9.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<Set<_i3.TableUpdate>> tableUpdates(
          [_i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i5.Stream<Set<_i3.TableUpdate>>.empty(),
      ) as _i5.Stream<Set<_i3.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
          _i5.FutureOr<T> Function(_i3.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_21<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
          _i3.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_22<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
          _i3.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_23<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_24<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_25<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
          Iterable<_i3.Expression<Object>>? columns) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectExpressions,
          [columns],
        ),
        returnValue: _FakeBaseSelectStatement_26<_i3.TypedResult>(
          this,
          Invocation.method(
            #selectExpressions,
            [columns],
          ),
        ),
      ) as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
          _i3.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_27<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i3.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i5.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
      ) as _i5.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_28<_i3.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_28<_i3.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i3.Selectable<_i3.QueryRow>);

  @override
  _i5.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_21<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #exclusively,
          [action],
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #exclusively,
                  [action],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_21<T>(
              this,
              Invocation.method(
                #exclusively,
                [action],
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runWithInterceptor,
          [action],
          {#interceptor: interceptor},
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #runWithInterceptor,
                  [action],
                  {#interceptor: interceptor},
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_21<T>(
              this,
              Invocation.method(
                #runWithInterceptor,
                [action],
                {#interceptor: interceptor},
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_29(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_29(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i3.GenerationContext);

  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #$expandVar,
            [
              start,
              amount,
            ],
          ),
        ),
      ) as String);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i6.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.FunctionsClient get functions => (super.noSuchMethod(
        Invocation.getter(#functions),
        returnValue: _FakeFunctionsClient_30(
          this,
          Invocation.getter(#functions),
        ),
      ) as _i6.FunctionsClient);

  @override
  set functions(_i6.FunctionsClient? _functions) => super.noSuchMethod(
        Invocation.setter(
          #functions,
          _functions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.SupabaseStorageClient get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeSupabaseStorageClient_31(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i6.SupabaseStorageClient);

  @override
  set storage(_i6.SupabaseStorageClient? _storage) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          _storage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.RealtimeClient get realtime => (super.noSuchMethod(
        Invocation.getter(#realtime),
        returnValue: _FakeRealtimeClient_32(
          this,
          Invocation.getter(#realtime),
        ),
      ) as _i6.RealtimeClient);

  @override
  set realtime(_i6.RealtimeClient? _realtime) => super.noSuchMethod(
        Invocation.setter(
          #realtime,
          _realtime,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.PostgrestClient get rest => (super.noSuchMethod(
        Invocation.getter(#rest),
        returnValue: _FakePostgrestClient_33(
          this,
          Invocation.getter(#rest),
        ),
      ) as _i6.PostgrestClient);

  @override
  set rest(_i6.PostgrestClient? _rest) => super.noSuchMethod(
        Invocation.setter(
          #rest,
          _rest,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
        Invocation.setter(
          #headers,
          headers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.GoTrueClient get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeGoTrueClient_34(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i6.GoTrueClient);

  @override
  _i6.SupabaseQueryBuilder from(String? table) => (super.noSuchMethod(
        Invocation.method(
          #from,
          [table],
        ),
        returnValue: _FakeSupabaseQueryBuilder_35(
          this,
          Invocation.method(
            #from,
            [table],
          ),
        ),
      ) as _i6.SupabaseQueryBuilder);

  @override
  _i6.SupabaseQuerySchema schema(String? schema) => (super.noSuchMethod(
        Invocation.method(
          #schema,
          [schema],
        ),
        returnValue: _FakeSupabaseQuerySchema_36(
          this,
          Invocation.method(
            #schema,
            [schema],
          ),
        ),
      ) as _i6.SupabaseQuerySchema);

  @override
  _i6.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rpc,
          [fn],
          {
            #params: params,
            #get: get,
          },
        ),
        returnValue: _FakePostgrestFilterBuilder_37<T>(
          this,
          Invocation.method(
            #rpc,
            [fn],
            {
              #params: params,
              #get: get,
            },
          ),
        ),
      ) as _i6.PostgrestFilterBuilder<T>);

  @override
  _i6.RealtimeChannel channel(
    String? name, {
    _i6.RealtimeChannelConfig? opts = const _i6.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #channel,
          [name],
          {#opts: opts},
        ),
        returnValue: _FakeRealtimeChannel_38(
          this,
          Invocation.method(
            #channel,
            [name],
            {#opts: opts},
          ),
        ),
      ) as _i6.RealtimeChannel);

  @override
  List<_i6.RealtimeChannel> getChannels() => (super.noSuchMethod(
        Invocation.method(
          #getChannels,
          [],
        ),
        returnValue: <_i6.RealtimeChannel>[],
      ) as List<_i6.RealtimeChannel>);

  @override
  _i5.Future<String> removeChannel(_i6.RealtimeChannel? channel) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeChannel,
          [channel],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #removeChannel,
            [channel],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<String>> removeAllChannels() => (super.noSuchMethod(
        Invocation.method(
          #removeAllChannels,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GoTrueClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoTrueClient extends _i1.Mock implements _i6.GoTrueClient {
  MockGoTrueClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GoTrueAdminApi get admin => (super.noSuchMethod(
        Invocation.getter(#admin),
        returnValue: _FakeGoTrueAdminApi_39(
          this,
          Invocation.getter(#admin),
        ),
      ) as _i6.GoTrueAdminApi);

  @override
  set admin(_i6.GoTrueAdminApi? _admin) => super.noSuchMethod(
        Invocation.setter(
          #admin,
          _admin,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.GoTrueMFAApi get mfa => (super.noSuchMethod(
        Invocation.getter(#mfa),
        returnValue: _FakeGoTrueMFAApi_40(
          this,
          Invocation.getter(#mfa),
        ),
      ) as _i6.GoTrueMFAApi);

  @override
  set mfa(_i6.GoTrueMFAApi? _mfa) => super.noSuchMethod(
        Invocation.setter(
          #mfa,
          _mfa,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<_i6.AuthState> get onAuthStateChange => (super.noSuchMethod(
        Invocation.getter(#onAuthStateChange),
        returnValue: _i5.Stream<_i6.AuthState>.empty(),
      ) as _i5.Stream<_i6.AuthState>);

  @override
  _i5.Stream<_i6.AuthState> get onAuthStateChangeSync => (super.noSuchMethod(
        Invocation.getter(#onAuthStateChangeSync),
        returnValue: _i5.Stream<_i6.AuthState>.empty(),
      ) as _i5.Stream<_i6.AuthState>);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i5.Future<_i6.AuthResponse> signInAnonymously({
    Map<String, dynamic>? data,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
          {
            #data: data,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i5.Future<_i6.AuthResponse>.value(_FakeAuthResponse_41(
          this,
          Invocation.method(
            #signInAnonymously,
            [],
            {
              #data: data,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i5.Future<_i6.AuthResponse>);

  @override
  _i5.Future<_i6.AuthResponse> signUp({
    String? email,
    String? phone,
    required String? password,
    String? emailRedirectTo,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i6.OtpChannel? channel = _i6.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #phone: phone,
            #password: password,
            #emailRedirectTo: emailRedirectTo,
            #data: data,
            #captchaToken: captchaToken,
            #channel: channel,
          },
        ),
        returnValue: _i5.Future<_i6.AuthResponse>.value(_FakeAuthResponse_41(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
              #emailRedirectTo: emailRedirectTo,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            },
          ),
        )),
      ) as _i5.Future<_i6.AuthResponse>);

  @override
  _i5.Future<_i6.AuthResponse> signInWithPassword({
    String? email,
    String? phone,
    required String? password,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithPassword,
          [],
          {
            #email: email,
            #phone: phone,
            #password: password,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i5.Future<_i6.AuthResponse>.value(_FakeAuthResponse_41(
          this,
          Invocation.method(
            #signInWithPassword,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i5.Future<_i6.AuthResponse>);

  @override
  _i5.Future<_i6.OAuthResponse> getOAuthSignInUrl({
    required _i6.OAuthProvider? provider,
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOAuthSignInUrl,
          [],
          {
            #provider: provider,
            #redirectTo: redirectTo,
            #scopes: scopes,
            #queryParams: queryParams,
          },
        ),
        returnValue: _i5.Future<_i6.OAuthResponse>.value(_FakeOAuthResponse_42(
          this,
          Invocation.method(
            #getOAuthSignInUrl,
            [],
            {
              #provider: provider,
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            },
          ),
        )),
      ) as _i5.Future<_i6.OAuthResponse>);

  @override
  _i5.Future<_i6.AuthSessionUrlResponse> exchangeCodeForSession(
          String? authCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #exchangeCodeForSession,
          [authCode],
        ),
        returnValue: _i5.Future<_i6.AuthSessionUrlResponse>.value(
            _FakeAuthSessionUrlResponse_43(
          this,
          Invocation.method(
            #exchangeCodeForSession,
            [authCode],
          ),
        )),
      ) as _i5.Future<_i6.AuthSessionUrlResponse>);

  @override
  _i5.Future<_i6.AuthResponse> signInWithIdToken({
    required _i6.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithIdToken,
          [],
          {
            #provider: provider,
            #idToken: idToken,
            #accessToken: accessToken,
            #nonce: nonce,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i5.Future<_i6.AuthResponse>.value(_FakeAuthResponse_41(
          this,
          Invocation.method(
            #signInWithIdToken,
            [],
            {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i5.Future<_i6.AuthResponse>);

  @override
  _i5.Future<void> signInWithOtp({
    String? email,
    String? phone,
    String? emailRedirectTo,
    bool? shouldCreateUser,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i6.OtpChannel? channel = _i6.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithOtp,
          [],
          {
            #email: email,
            #phone: phone,
            #emailRedirectTo: emailRedirectTo,
            #shouldCreateUser: shouldCreateUser,
            #data: data,
            #captchaToken: captchaToken,
            #channel: channel,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.AuthResponse> verifyOTP({
    String? email,
    String? phone,
    String? token,
    required _i6.OtpType? type,
    String? redirectTo,
    String? captchaToken,
    String? tokenHash,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOTP,
          [],
          {
            #email: email,
            #phone: phone,
            #token: token,
            #type: type,
            #redirectTo: redirectTo,
            #captchaToken: captchaToken,
            #tokenHash: tokenHash,
          },
        ),
        returnValue: _i5.Future<_i6.AuthResponse>.value(_FakeAuthResponse_41(
          this,
          Invocation.method(
            #verifyOTP,
            [],
            {
              #email: email,
              #phone: phone,
              #token: token,
              #type: type,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
              #tokenHash: tokenHash,
            },
          ),
        )),
      ) as _i5.Future<_i6.AuthResponse>);

  @override
  _i5.Future<String> getSSOSignInUrl({
    String? providerId,
    String? domain,
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSSOSignInUrl,
          [],
          {
            #providerId: providerId,
            #domain: domain,
            #redirectTo: redirectTo,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getSSOSignInUrl,
            [],
            {
              #providerId: providerId,
              #domain: domain,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i6.AuthResponse> refreshSession([String? refreshToken]) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshSession,
          [refreshToken],
        ),
        returnValue: _i5.Future<_i6.AuthResponse>.value(_FakeAuthResponse_41(
          this,
          Invocation.method(
            #refreshSession,
            [refreshToken],
          ),
        )),
      ) as _i5.Future<_i6.AuthResponse>);

  @override
  _i5.Future<void> reauthenticate() => (super.noSuchMethod(
        Invocation.method(
          #reauthenticate,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.ResendResponse> resend({
    String? email,
    String? phone,
    required _i6.OtpType? type,
    String? emailRedirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resend,
          [],
          {
            #email: email,
            #phone: phone,
            #type: type,
            #emailRedirectTo: emailRedirectTo,
            #captchaToken: captchaToken,
          },
        ),
        returnValue:
            _i5.Future<_i6.ResendResponse>.value(_FakeResendResponse_44(
          this,
          Invocation.method(
            #resend,
            [],
            {
              #email: email,
              #phone: phone,
              #type: type,
              #emailRedirectTo: emailRedirectTo,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i5.Future<_i6.ResendResponse>);

  @override
  _i5.Future<_i6.UserResponse> getUser([String? jwt]) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [jwt],
        ),
        returnValue: _i5.Future<_i6.UserResponse>.value(_FakeUserResponse_45(
          this,
          Invocation.method(
            #getUser,
            [jwt],
          ),
        )),
      ) as _i5.Future<_i6.UserResponse>);

  @override
  _i5.Future<_i6.UserResponse> updateUser(
    _i6.UserAttributes? attributes, {
    String? emailRedirectTo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [attributes],
          {#emailRedirectTo: emailRedirectTo},
        ),
        returnValue: _i5.Future<_i6.UserResponse>.value(_FakeUserResponse_45(
          this,
          Invocation.method(
            #updateUser,
            [attributes],
            {#emailRedirectTo: emailRedirectTo},
          ),
        )),
      ) as _i5.Future<_i6.UserResponse>);

  @override
  _i5.Future<_i6.AuthResponse> setSession(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSession,
          [refreshToken],
        ),
        returnValue: _i5.Future<_i6.AuthResponse>.value(_FakeAuthResponse_41(
          this,
          Invocation.method(
            #setSession,
            [refreshToken],
          ),
        )),
      ) as _i5.Future<_i6.AuthResponse>);

  @override
  _i5.Future<_i6.AuthSessionUrlResponse> getSessionFromUrl(
    Uri? originUrl, {
    bool? storeSession = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionFromUrl,
          [originUrl],
          {#storeSession: storeSession},
        ),
        returnValue: _i5.Future<_i6.AuthSessionUrlResponse>.value(
            _FakeAuthSessionUrlResponse_43(
          this,
          Invocation.method(
            #getSessionFromUrl,
            [originUrl],
            {#storeSession: storeSession},
          ),
        )),
      ) as _i5.Future<_i6.AuthSessionUrlResponse>);

  @override
  _i5.Future<void> signOut(
          {_i6.SignOutScope? scope = _i6.SignOutScope.local}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
          {#scope: scope},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetPasswordForEmail(
    String? email, {
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPasswordForEmail,
          [email],
          {
            #redirectTo: redirectTo,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.UserIdentity>> getUserIdentities() => (super.noSuchMethod(
        Invocation.method(
          #getUserIdentities,
          [],
        ),
        returnValue:
            _i5.Future<List<_i6.UserIdentity>>.value(<_i6.UserIdentity>[]),
      ) as _i5.Future<List<_i6.UserIdentity>>);

  @override
  _i5.Future<_i6.OAuthResponse> getLinkIdentityUrl(
    _i6.OAuthProvider? provider, {
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLinkIdentityUrl,
          [provider],
          {
            #redirectTo: redirectTo,
            #scopes: scopes,
            #queryParams: queryParams,
          },
        ),
        returnValue: _i5.Future<_i6.OAuthResponse>.value(_FakeOAuthResponse_42(
          this,
          Invocation.method(
            #getLinkIdentityUrl,
            [provider],
            {
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            },
          ),
        )),
      ) as _i5.Future<_i6.OAuthResponse>);

  @override
  _i5.Future<void> unlinkIdentity(_i6.UserIdentity? identity) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlinkIdentity,
          [identity],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setInitialSession(String? jsonStr) => (super.noSuchMethod(
        Invocation.method(
          #setInitialSession,
          [jsonStr],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.AuthResponse> recoverSession(String? jsonStr) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverSession,
          [jsonStr],
        ),
        returnValue: _i5.Future<_i6.AuthResponse>.value(_FakeAuthResponse_41(
          this,
          Invocation.method(
            #recoverSession,
            [jsonStr],
          ),
        )),
      ) as _i5.Future<_i6.AuthResponse>);

  @override
  void startAutoRefresh() => super.noSuchMethod(
        Invocation.method(
          #startAutoRefresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopAutoRefresh() => super.noSuchMethod(
        Invocation.method(
          #stopAutoRefresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyAllSubscribers(
    _i6.AuthChangeEvent? event, {
    _i6.Session? session,
    bool? broadcast = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #notifyAllSubscribers,
          [event],
          {
            #session: session,
            #broadcast: broadcast,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  Object notifyException(
    Object? exception, [
    StackTrace? stackTrace,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyException,
          [
            exception,
            stackTrace,
          ],
        ),
        returnValue: _FakeObject_46(
          this,
          Invocation.method(
            #notifyException,
            [
              exception,
              stackTrace,
            ],
          ),
        ),
      ) as Object);
}

/// A class which mocks [SupabaseStorageClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseStorageClient extends _i1.Mock
    implements _i6.SupabaseStorageClient {
  MockSupabaseStorageClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i7.Fetch get storageFetch => (super.noSuchMethod(
        Invocation.getter(#storageFetch),
        returnValue: _FakeFetch_47(
          this,
          Invocation.getter(#storageFetch),
        ),
      ) as _i7.Fetch);

  @override
  set storageFetch(_i7.Fetch? _storageFetch) => super.noSuchMethod(
        Invocation.setter(
          #storageFetch,
          _storageFetch,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.StorageFileApi from(String? id) => (super.noSuchMethod(
        Invocation.method(
          #from,
          [id],
        ),
        returnValue: _FakeStorageFileApi_48(
          this,
          Invocation.method(
            #from,
            [id],
          ),
        ),
      ) as _i6.StorageFileApi);

  @override
  void setAuth(String? jwt) => super.noSuchMethod(
        Invocation.method(
          #setAuth,
          [jwt],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<List<_i6.Bucket>> listBuckets() => (super.noSuchMethod(
        Invocation.method(
          #listBuckets,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Bucket>>.value(<_i6.Bucket>[]),
      ) as _i5.Future<List<_i6.Bucket>>);

  @override
  _i5.Future<_i6.Bucket> getBucket(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getBucket,
          [id],
        ),
        returnValue: _i5.Future<_i6.Bucket>.value(_FakeBucket_49(
          this,
          Invocation.method(
            #getBucket,
            [id],
          ),
        )),
      ) as _i5.Future<_i6.Bucket>);

  @override
  _i5.Future<String> createBucket(
    String? id, [
    _i6.BucketOptions? bucketOptions = const _i6.BucketOptions(public: false),
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBucket,
          [
            id,
            bucketOptions,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #createBucket,
            [
              id,
              bucketOptions,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> updateBucket(
    String? id,
    _i6.BucketOptions? bucketOptions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBucket,
          [
            id,
            bucketOptions,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #updateBucket,
            [
              id,
              bucketOptions,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> emptyBucket(String? id) => (super.noSuchMethod(
        Invocation.method(
          #emptyBucket,
          [id],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #emptyBucket,
            [id],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> deleteBucket(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBucket,
          [id],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #deleteBucket,
            [id],
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [StorageFileApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageFileApi extends _i1.Mock implements _i6.StorageFileApi {
  MockStorageFileApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i5.Future<String> upload(
    String? path,
    _i14.File? file, {
    _i6.FileOptions? fileOptions = const _i6.FileOptions(),
    int? retryAttempts,
    _i6.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upload,
          [
            path,
            file,
          ],
          {
            #fileOptions: fileOptions,
            #retryAttempts: retryAttempts,
            #retryController: retryController,
          },
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #upload,
            [
              path,
              file,
            ],
            {
              #fileOptions: fileOptions,
              #retryAttempts: retryAttempts,
              #retryController: retryController,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> uploadBinary(
    String? path,
    _i15.Uint8List? data, {
    _i6.FileOptions? fileOptions = const _i6.FileOptions(),
    int? retryAttempts,
    _i6.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBinary,
          [
            path,
            data,
          ],
          {
            #fileOptions: fileOptions,
            #retryAttempts: retryAttempts,
            #retryController: retryController,
          },
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #uploadBinary,
            [
              path,
              data,
            ],
            {
              #fileOptions: fileOptions,
              #retryAttempts: retryAttempts,
              #retryController: retryController,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> uploadToSignedUrl(
    String? path,
    String? token,
    _i14.File? file, [
    _i6.FileOptions? fileOptions = const _i6.FileOptions(),
    int? retryAttempts,
    _i6.StorageRetryController? retryController,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadToSignedUrl,
          [
            path,
            token,
            file,
            fileOptions,
            retryAttempts,
            retryController,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #uploadToSignedUrl,
            [
              path,
              token,
              file,
              fileOptions,
              retryAttempts,
              retryController,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> uploadBinaryToSignedUrl(
    String? path,
    String? token,
    _i15.Uint8List? data, [
    _i6.FileOptions? fileOptions = const _i6.FileOptions(),
    int? retryAttempts,
    _i6.StorageRetryController? retryController,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBinaryToSignedUrl,
          [
            path,
            token,
            data,
            fileOptions,
            retryAttempts,
            retryController,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #uploadBinaryToSignedUrl,
            [
              path,
              token,
              data,
              fileOptions,
              retryAttempts,
              retryController,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i6.SignedUploadURLResponse> createSignedUploadUrl(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSignedUploadUrl,
          [path],
        ),
        returnValue: _i5.Future<_i6.SignedUploadURLResponse>.value(
            _FakeSignedUploadURLResponse_50(
          this,
          Invocation.method(
            #createSignedUploadUrl,
            [path],
          ),
        )),
      ) as _i5.Future<_i6.SignedUploadURLResponse>);

  @override
  _i5.Future<String> update(
    String? path,
    _i14.File? file, {
    _i6.FileOptions? fileOptions = const _i6.FileOptions(),
    int? retryAttempts,
    _i6.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            path,
            file,
          ],
          {
            #fileOptions: fileOptions,
            #retryAttempts: retryAttempts,
            #retryController: retryController,
          },
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #update,
            [
              path,
              file,
            ],
            {
              #fileOptions: fileOptions,
              #retryAttempts: retryAttempts,
              #retryController: retryController,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> updateBinary(
    String? path,
    _i15.Uint8List? data, {
    _i6.FileOptions? fileOptions = const _i6.FileOptions(),
    int? retryAttempts,
    _i6.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBinary,
          [
            path,
            data,
          ],
          {
            #fileOptions: fileOptions,
            #retryAttempts: retryAttempts,
            #retryController: retryController,
          },
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #updateBinary,
            [
              path,
              data,
            ],
            {
              #fileOptions: fileOptions,
              #retryAttempts: retryAttempts,
              #retryController: retryController,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> move(
    String? fromPath,
    String? toPath, {
    String? destinationBucket,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #move,
          [
            fromPath,
            toPath,
          ],
          {#destinationBucket: destinationBucket},
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #move,
            [
              fromPath,
              toPath,
            ],
            {#destinationBucket: destinationBucket},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> copy(
    String? fromPath,
    String? toPath, {
    String? destinationBucket,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copy,
          [
            fromPath,
            toPath,
          ],
          {#destinationBucket: destinationBucket},
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #copy,
            [
              fromPath,
              toPath,
            ],
            {#destinationBucket: destinationBucket},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> createSignedUrl(
    String? path,
    int? expiresIn, {
    _i6.TransformOptions? transform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSignedUrl,
          [
            path,
            expiresIn,
          ],
          {#transform: transform},
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #createSignedUrl,
            [
              path,
              expiresIn,
            ],
            {#transform: transform},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<_i6.SignedUrl>> createSignedUrls(
    List<String>? paths,
    int? expiresIn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSignedUrls,
          [
            paths,
            expiresIn,
          ],
        ),
        returnValue: _i5.Future<List<_i6.SignedUrl>>.value(<_i6.SignedUrl>[]),
      ) as _i5.Future<List<_i6.SignedUrl>>);

  @override
  _i5.Future<_i15.Uint8List> download(
    String? path, {
    _i6.TransformOptions? transform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [path],
          {#transform: transform},
        ),
        returnValue: _i5.Future<_i15.Uint8List>.value(_i15.Uint8List(0)),
      ) as _i5.Future<_i15.Uint8List>);

  @override
  String getPublicUrl(
    String? path, {
    _i6.TransformOptions? transform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicUrl,
          [path],
          {#transform: transform},
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #getPublicUrl,
            [path],
            {#transform: transform},
          ),
        ),
      ) as String);

  @override
  _i5.Future<List<_i6.FileObject>> remove(List<String>? paths) =>
      (super.noSuchMethod(
        Invocation.method(
          #remove,
          [paths],
        ),
        returnValue: _i5.Future<List<_i6.FileObject>>.value(<_i6.FileObject>[]),
      ) as _i5.Future<List<_i6.FileObject>>);

  @override
  _i5.Future<List<_i6.FileObject>> list({
    String? path,
    _i6.SearchOptions? searchOptions = const _i6.SearchOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #list,
          [],
          {
            #path: path,
            #searchOptions: searchOptions,
          },
        ),
        returnValue: _i5.Future<List<_i6.FileObject>>.value(<_i6.FileObject>[]),
      ) as _i5.Future<List<_i6.FileObject>>);
}
